import Link from "next/link";
import { notFound } from "next/navigation";
import { createAgentCabinetService } from "@/src/modules/agent-cabinet";
import { getAgentCabinetLocale } from "@/src/modules/agent-cabinet/locale";
import { agentDate, attributionStatus, attributionStatusTone, eventLabel, maskedContact, referralNextAction } from "@/src/modules/agent-cabinet/operational-presentation";
import { AgentPageHeader, secondaryButton } from "@/src/modules/agent-cabinet/components/PageHeader";
import { ReferralStatusBadge } from "@/src/modules/agent-cabinet/components/StatusBadge";
import { CabinetStatusBadge, OperationalTimeline, cabinetPageNarrow, cabinetSurface, cabinetTextAction } from "@/src/modules/cabinet-experience/components";

export default async function AgentReferralDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [item, locale] = await Promise.all([createAgentCabinetService().referral((await params).id), getAgentCabinetLocale()]); if (!item) notFound(); const ro = locale === "ro"; const reason = item.duplicateReason ?? item.existingCustomerReason;
  return <main className={cabinetPageNarrow}><AgentPageHeader title={`${ro ? "Recomandare" : "Рекомендация"} #${item.id.slice(0,8).toUpperCase()}`} actions={<Link className={secondaryButton} href="/agent/referrals">{ro ? "Toate recomandările" : "Все рекомендации"}</Link>}/>
    <section className={`p-4 sm:p-5 ${cabinetSurface}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">{item.name}</h2><p className="mt-1 text-sm text-zinc-500">{agentDate(item.submittedAt, locale, true)}</p></div><ReferralStatusBadge locale={locale} status={item.status}/></div><p className="mt-4 text-sm font-semibold text-emerald-700">{referralNextAction(item, locale)}</p>{reason ? <p className="mt-3 border-l-2 border-amber-500 pl-3 text-sm">{reason}</p> : null}</section>
    <section><h2 className="mb-3 font-semibold">{ro ? "Recomandare" : "Рекомендация"}</h2><dl className="grid gap-px overflow-hidden rounded-xl border border-zinc-200 bg-zinc-200 sm:grid-cols-2">{[[ro ? "Contact" : "Контакт", maskedContact(item.phone,item.email,locale)],[ro ? "Localitate" : "Населённый пункт",item.locality??"—"],[ro ? "Tip obiect" : "Тип объекта",item.objectType??"—"],[ro ? "Necesitate" : "Потребность",item.needSummary]].map(([a,b])=><div className="bg-white p-4" key={a}><dt className="text-xs text-zinc-500">{a}</dt><dd className="mt-1 text-sm">{b}</dd></div>)}</dl></section>
    <section className={`p-4 sm:p-5 ${cabinetSurface}`}><h2 className="font-semibold">{ro ? "Atribuire" : "Закрепление"}</h2><div className="mt-2"><CabinetStatusBadge label={attributionStatus(item.attributionStatus, locale)} tone={attributionStatusTone(item.attributionStatus)} /></div>{item.protectionUntil ? <p className="mt-2 text-xs text-zinc-500">{ro ? "Protecție până la" : "Защита до"} {agentDate(item.protectionUntil, locale, true)}</p> : <p className="mt-2 text-xs text-zinc-500">{ro ? "Atribuirea va apărea după verificare." : "Закрепление появится после проверки."}</p>}{item.attributionId ? <Link className={`${cabinetTextAction} mt-2`} href={`/agent/clients/${item.attributionId}`}>{ro ? "Deschide clientul" : "Открыть клиента"}</Link> : null}</section>
    <section className={`p-4 sm:p-5 ${cabinetSurface}`}><h2 className="mb-4 text-lg font-semibold tracking-tight">{ro ? "Evoluție cunoscută" : "Известное движение"}</h2><OperationalTimeline items={(item.events?.length ? item.events : [{id:item.id,type:"REFERRAL_CAPTURED",createdAt:item.submittedAt}]).map(event => ({ id:event.id, label:eventLabel(event.type,locale), date:agentDate(event.createdAt,locale,true) }))}/></section>
  </main>;
}
