import { redirect } from "next/navigation";

import { getPartnerWorkspaceContextAction } from "@/src/modules/partner-cabinet/actions/workspace-context.action";
import { respondInstallationOfferAction, transitionPartnerInstallationExecutionAction } from "@/src/modules/retail-marketplace/actions";
import { getInstallationAssignmentDispatcher } from "@/src/modules/retail-marketplace/server";
import type { InstallationAssignmentView, PartnerInstallationAssignmentDto } from "@/src/modules/retail-marketplace/types";

const views: Array<{ key: InstallationAssignmentView; label: string }> = [
  { key: "offers", label: "Предложения" }, { key: "active", label: "Активные" }, { key: "completed", label: "Завершённые" },
];
const scopeLabels: Record<string, string> = { camera_installation: "Монтаж камер", cable_laying: "Прокладка кабеля", commissioning: "Пусконаладка", remote_configuration: "Удалённая настройка" };
const executionLabels: Record<string, string> = { scheduling: "Нужно назначить дату", scheduled: "Монтаж запланирован", in_progress: "Работы выполняются", completed_by_provider: "Работы завершены", customer_confirmation_pending: "Ожидается подтверждение заказчика", customer_confirmed: "Подтверждено заказчиком", issue_reported: "Заказчик сообщил о проблеме", disputed: "Обращение рассматривается", resolved: "Обращение решено", cancelled: "Монтаж отменён" };

export default async function InstallationOrdersPage({ searchParams }: { searchParams: Promise<{ view?: string; result?: string }> }) {
  const [context, query] = await Promise.all([getPartnerWorkspaceContextAction(), searchParams]);
  if (!context.success || !context.data.companyId || context.data.accessState !== "active") redirect("/cabinet");
  const view = views.some((entry) => entry.key === query.view) ? query.view as InstallationAssignmentView : "offers";
  const assignments = await getInstallationAssignmentDispatcher().list(context.data.companyId, view);
  return <main className="mx-auto max-w-6xl space-y-6">
    <header><p className="text-xs font-semibold uppercase text-emerald-700">Installation Marketplace</p><h1 className="mt-1 text-2xl font-semibold">Заказы на монтаж</h1><p className="mt-2 text-sm text-zinc-600">Предложения по монтажу CCTV для вашей команды. До принятия показывается только необходимый объём работ.</p></header>
    {query.result ? <p role="status" className="border-l-4 border-emerald-600 bg-emerald-50 p-3 text-sm">{query.result === "accept" ? "Предложение принято." : query.result === "updated" ? "Состояние монтажных работ обновлено." : "Отказ сохранён, заказ передан на повторное назначение."}</p> : null}
    <nav aria-label="Состояние монтажных заказов" className="flex flex-wrap gap-2">{views.map((entry) => <a aria-current={view === entry.key ? "page" : undefined} className={`inline-flex min-h-11 items-center rounded-md border px-4 text-sm font-semibold ${view === entry.key ? "border-emerald-700 bg-emerald-700 text-white" : "border-zinc-300 bg-white"}`} href={`/cabinet/installation-orders?view=${entry.key}`} key={entry.key}>{entry.label}</a>)}</nav>
    {assignments.length ? <div className="grid gap-4">{assignments.map((assignment) => <AssignmentCard assignment={assignment} key={assignment.attemptId} />)}</div> : <p className="border border-zinc-200 bg-white p-6 text-sm text-zinc-600">В этом разделе пока нет монтажных заказов.</p>}
  </main>;
}

function AssignmentCard({ assignment }: { assignment: PartnerInstallationAssignmentDto }) {
  const deadline = new Intl.DateTimeFormat("ru-MD", { dateStyle: "medium", timeStyle: "short" }).format(new Date(assignment.deadlineAt));
  return <article className="grid gap-4 border border-zinc-200 bg-white p-4 lg:grid-cols-[minmax(0,1fr)_auto]">
    <div className="min-w-0 space-y-3"><div className="flex flex-wrap items-center gap-2"><span className="rounded bg-zinc-100 px-2 py-1 text-xs font-semibold">CCTV</span><h2 className="font-semibold">{assignment.orderNumber} · {assignment.locality}</h2>{assignment.execution ? <span className="rounded bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-800">{executionLabels[assignment.execution.state]}</span> : null}</div>
      <dl className="grid gap-2 text-sm sm:grid-cols-2">{assignment.scope.map((line) => <div className="flex justify-between gap-4 border-b border-zinc-100 py-1" key={line.serviceType}><dt>{scopeLabels[line.serviceType] ?? line.serviceType}</dt><dd className="font-medium">{line.quantity} {line.unitCode === "meter" ? "м" : line.unitCode === "service" ? "услуга" : "шт."}</dd></div>)}</dl>
      {assignment.status === "offered" ? <p className="text-sm text-amber-800">Ответить до {deadline}</p> : null}
      {assignment.status === "accepted" && assignment.customer && assignment.exactAddress ? <div className="border-l-4 border-emerald-600 bg-emerald-50 p-3 text-sm"><p className="font-semibold">Контакт после принятия</p><p>{assignment.customer.name}, {assignment.customer.phone}</p><p>{assignment.exactAddress.locality}, {assignment.exactAddress.street} {assignment.exactAddress.building}</p></div> : null}
      {assignment.execution?.scheduledStartAt ? <p className="text-sm"><strong>Дата:</strong> {new Intl.DateTimeFormat("ru-MD", { dateStyle: "long", timeStyle: "short", timeZone: "Europe/Chisinau" }).format(new Date(assignment.execution.scheduledStartAt))}{assignment.execution.scheduledEndAt ? ` — ${new Intl.DateTimeFormat("ru-MD", { timeStyle: "short", timeZone: "Europe/Chisinau" }).format(new Date(assignment.execution.scheduledEndAt))}` : ""}</p> : null}
    </div>
    {assignment.status === "offered" ? <div className="flex min-w-56 flex-col gap-2"><form action={respondInstallationOfferAction}><input name="attemptId" type="hidden" value={assignment.attemptId}/><input name="decision" type="hidden" value="accept"/><input name="idempotencyKey" type="hidden" value={crypto.randomUUID()}/><button className="min-h-11 w-full rounded-md bg-emerald-700 px-4 text-sm font-semibold text-white" type="submit">Принять</button></form>
      <details><summary className="flex min-h-11 cursor-pointer items-center justify-center rounded-md border border-zinc-300 px-4 text-sm font-semibold">Отказаться</summary><form action={respondInstallationOfferAction} className="mt-2 grid gap-2"><input name="attemptId" type="hidden" value={assignment.attemptId}/><input name="decision" type="hidden" value="decline"/><input name="idempotencyKey" type="hidden" value={crypto.randomUUID()}/><select aria-label="Причина отказа" className="min-h-11 rounded-md border border-zinc-300 px-3 text-sm" name="reasonCode"><option value="">Без причины</option><option value="no_capacity">Нет свободной команды</option><option value="schedule_conflict">Не подходит срок</option><option value="region_issue">Регион</option><option value="technical_scope">Технический объём</option><option value="other">Другое</option></select><button className="min-h-11 rounded-md border border-zinc-900 px-4 text-sm font-semibold" type="submit">Подтвердить отказ</button></form></details></div> : null}
    {assignment.execution ? <ExecutionActions execution={assignment.execution} /> : null}
  </article>;
}

function ExecutionActions({ execution }: { execution: NonNullable<PartnerInstallationAssignmentDto["execution"]> }) {
  if (execution.state === "scheduling" || execution.state === "scheduled") return <div className="min-w-64"><details><summary className="flex min-h-11 cursor-pointer items-center justify-center rounded-md bg-emerald-700 px-4 text-sm font-semibold text-white">{execution.state === "scheduled" ? "Изменить дату" : "Назначить дату"}</summary><form action={transitionPartnerInstallationExecutionAction} className="mt-2 grid gap-2"><CommandFields command="schedule" execution={execution}/><label className="grid gap-1 text-xs"><span>Дата и время</span><input className="min-h-11 border border-zinc-300 px-3 text-sm" name="scheduledStartAt" required type="datetime-local"/></label><label className="grid gap-1 text-xs"><span>Окончание окна, необязательно</span><input className="min-h-11 border border-zinc-300 px-3 text-sm" name="scheduledEndAt" type="datetime-local"/></label><input className="min-h-11 border border-zinc-300 px-3 text-sm" maxLength={500} name="note" placeholder="Короткое примечание"/><button className="min-h-11 border border-zinc-900 px-4 text-sm font-semibold">Сохранить дату</button></form></details>{execution.state === "scheduled" ? <SimpleExecutionCommand execution={execution}/> : null}</div>;
  if (execution.state === "in_progress") return <form action={transitionPartnerInstallationExecutionAction} className="grid min-w-64 gap-2"><CommandFields command="complete" execution={execution}/><input className="min-h-11 border border-zinc-300 px-3 text-sm" maxLength={500} name="note" placeholder="Примечание, необязательно"/><button className="min-h-11 rounded-md bg-emerald-700 px-4 text-sm font-semibold text-white">Завершить работы</button></form>;
  return null;
}
function CommandFields({ command, execution }: { command: "schedule" | "start" | "complete"; execution: NonNullable<PartnerInstallationAssignmentDto["execution"]> }) { return <><input name="executionId" type="hidden" value={execution.id}/><input name="command" type="hidden" value={command}/><input name="revision" type="hidden" value={execution.revision}/><input name="idempotencyKey" type="hidden" value={crypto.randomUUID()}/></>; }
function SimpleExecutionCommand({ execution }: { execution: NonNullable<PartnerInstallationAssignmentDto["execution"]> }) { return <form action={transitionPartnerInstallationExecutionAction} className="mt-2"><CommandFields command="start" execution={execution}/><button className="min-h-11 w-full rounded-md bg-emerald-700 px-4 text-sm font-semibold text-white">Начать работы</button></form>; }
