import { definePartnerCopy } from "./define-copy";

export const getProposalGuidedCopy = definePartnerCopy({
  objectStep: "Шаг 1 · Объект", objectQuestion: "Что нужно защитить?", zonesStep: "Шаг 2 · Зоны наблюдения", requirementsStep: "Шаг 3 · Требования к системе",
  suggestions: "Добавьте нужные зоны", allZones: "Другие зоны", zoneName: "Название зоны", zonePlacement: "Расположение", indoor: "Внутри", outdoor: "Снаружи", points: "Точек наблюдения", zones: "Зоны", remove: "Удалить зону", zoneOptions: "Требования зоны",
  entrance: "Вход / выход", perimeter: "Периметр", parking: "Парковка", gate: "Ворота / въезд", checkout: "Касса", reception: "Ресепшн", sales: "Торговый зал", office: "Офис / кабинет", corridor: "Коридор", storage: "Склад", production: "Производственная зона", loading: "Погрузка", inside: "Внутри", custom: "Другое", warehouseStorage: "Зона хранения",
  detail: "Детализация изображения", basic: "Базовая", standard: "Стандарт", detailed: "Детально", maximum: "Максимальная детализация", separate: "Настроить отдельно", archive: "Архив записи", capabilities: "Дополнительные возможности", services: "Услуги", installation: "Монтаж", commissioning: "Пусконаладка", remote: "Настройка удалённого просмотра", phone: "Просмотр с телефона", advanced: "Дополнительные настройки", autoRecorder: "Регистратор: Подобрать автоматически", cableLater: "Рассчитать позже", cableManual: "Указать ориентировочно", demand: "Требования к системе", empty: "Добавьте хотя бы одну точку наблюдения", select: "Подобрать систему", description: "Описать задачу", recommended: "Рекомендуется", progressOf: "из 4", proposed: "Предложенная система", cameras: "Камеры", network: "Сеть / PoE", noExtras: "Не выбраны",
}, {
  objectStep: "Pasul 1 · Obiect", objectQuestion: "Ce trebuie protejat?", zonesStep: "Pasul 2 · Zone de supraveghere", requirementsStep: "Pasul 3 · Cerințe de sistem",
  suggestions: "Adăugați zonele necesare", allZones: "Alte zone", zoneName: "Denumirea zonei", zonePlacement: "Amplasare", indoor: "Interior", outdoor: "Exterior", points: "Puncte de supraveghere", zones: "Zone", remove: "Eliminați zona", zoneOptions: "Cerințe pentru zonă",
  entrance: "Intrare / ieșire", perimeter: "Perimetru", parking: "Parcare", gate: "Poartă / acces auto", checkout: "Casă", reception: "Recepție", sales: "Sală de vânzare", office: "Birou", corridor: "Coridor", storage: "Depozit", production: "Zonă de producție", loading: "Încărcare", inside: "Interior", custom: "Alta", warehouseStorage: "Zonă de depozitare",
  detail: "Detaliile imaginii", basic: "De bază", standard: "Standard", detailed: "Detaliat", maximum: "Detaliere maximă", separate: "Configurați separat", archive: "Arhiva înregistrărilor", capabilities: "Funcții suplimentare", services: "Servicii", installation: "Instalare", commissioning: "Punere în funcțiune", remote: "Configurarea vizualizării la distanță", phone: "Vizualizare de pe telefon", advanced: "Setări suplimentare", autoRecorder: "Recorder: Selectare automată", cableLater: "Calculați mai târziu", cableManual: "Indicați orientativ", demand: "Cerințe de sistem", empty: "Adăugați cel puțin un punct de supraveghere", select: "Selectați sistemul", description: "Descrieți sarcina", recommended: "Recomandat", progressOf: "din 4", proposed: "Sistem propus", cameras: "Camere", network: "Rețea / PoE", noExtras: "Nu sunt selectate",
});
