export const businessTerms = {
  company: "Компания",
  partner: "Партнёр",
  employee: "Сотрудник",
  owner: "Владелец",
  manager: "Менеджер",
  buyer: "Покупатель",
  accountant: "Бухгалтер",
  observer: "Наблюдатель",
  partnerPrice: "Ваша цена",
  retailPrice: "Розничная цена",
  inStock: "В наличии",
  expectedArrival: "Ожидается к поступлению",
  outOfStock: "Нет в наличии",
  order: "Заказ",
  plannedShipment: "Планируемая отгрузка",
  dateChange: "Перенос даты",
  estimate: "Смета",
  proposal: "Коммерческое предложение",
  favorites: "Избранное",
  comparison: "Сравнение",
  finance: "Финансы",
  payable: "К оплате",
  advance: "Аванс",
  accessRequest: "Заявка на доступ",
  synchronization: "Синхронизация",
  incident: "Инцидент",
} as const;

export type BusinessTerm = keyof typeof businessTerms;
