import Link from "next/link";
import { ArrowRight, FileText, Headphones, PackageCheck, ReceiptText, ShoppingBag } from "lucide-react";
import { createFinalCustomerService, getFinalCustomerContext } from "@/src/modules/final-customer/server";
import { getFinalCustomerLocale } from "@/src/modules/final-customer/locale";
import { customerMoney, orderStatus, paymentStatus, serviceStatusLabel } from "@/src/modules/final-customer/presentation";

export default async function FinalCustomerOverviewPage() {
  const [context, locale] = await Promise.all([getFinalCustomerContext(), getFinalCustomerLocale()]);
  const service = createFinalCustomerService();
  const overview = await service.commandCenter(context.account);
  const ro = locale === "ro";
  const cards = [
    { href: "/account/orders", title: ro ? "Comenzi" : "Заказы", Icon: ReceiptText, body: overview.latestOrder ? `${overview.latestOrder.number} · ${orderStatus(overview.latestOrder.status, locale)} · ${paymentStatus(overview.latestOrder.paymentState, locale)} · ${customerMoney(overview.latestOrder.total, overview.latestOrder.currency, locale)}` : (ro ? "Nu există comenzi asociate" : "Связанных заказов нет") },
    { href: "/account/purchases", title: ro ? "Cumpărături" : "Покупки", Icon: ShoppingBag, body: overview.recentPurchases.length ? `${ro ? "Ultimele produse" : "Последние товары"}: ${overview.recentPurchases.map((item) => item.name).slice(0, 2).join(", ")}` : (ro ? "Nu există cumpărături confirmate" : "Нет подтверждённых покупок") },
    { href: "/account/equipment", title: ro ? "Echipamente și garanție" : "Оборудование и гарантия", Icon: PackageCheck, body: overview.equipmentCount ? `${overview.equipmentCount} ${ro ? "poziții confirmate" : "подтверждённых позиций"}` : (ro ? "Echipamentele vor apărea după cumpărare" : "Оборудование появится после покупки") },
    { href: "/account/documents", title: ro ? "Documente" : "Документы", Icon: FileText, body: `${overview.documentCount} ${ro ? "documente disponibile" : "доступных документов"}` },
    { href: "/account/service", title: ro ? "Service" : "Сервис", Icon: Headphones, body: overview.serviceNeedsInfoCount > 0 ? `${ro ? "Necesită răspuns" : "Требует ответа"}: ${overview.serviceNeedsInfoCount}` : overview.activeServiceRequestCount > 0 ? `${ro ? "Solicitări active" : "Активные обращения"}: ${overview.activeServiceRequestCount}` : overview.latestRequest ? `${overview.latestRequest.number} · ${serviceStatusLabel(overview.latestRequest.status, locale)}` : (ro ? "Creați o solicitare de service" : "Создать сервисное обращение") },
  ];
  return <main className="mx-auto max-w-5xl space-y-5 px-4 py-6 sm:py-8"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-zinc-500">{ro ? "Bună ziua" : "Здравствуйте"}</p><h1 className="text-2xl font-semibold tracking-tight">{overview.displayName ?? (ro ? "Cont personal" : "Личный кабинет")}</h1><p className="mt-1 text-sm text-zinc-600">{ro ? "Comenzile, cumpărăturile, documentele și solicitările dvs. într-un singur loc." : "Заказы, покупки, документы и обращения в одном месте."}</p></div><div className="flex flex-col gap-2 sm:flex-row"><Link className="inline-flex min-h-11 items-center justify-center rounded-lg bg-zinc-950 px-4 text-sm font-semibold text-white" href={`/catalog?lang=${locale}&view=all`}>{ro ? "Deschide catalogul" : "Открыть каталог"}</Link><Link className="inline-flex min-h-11 items-center justify-center rounded-lg border border-zinc-300 px-4 text-sm font-semibold" href="/account/service/new">{ro ? "Solicitare de service" : "Обратиться в сервис"}</Link></div></header><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{cards.map(({ href, title, Icon, body }) => <Link className="group flex min-h-36 flex-col rounded-xl border border-zinc-200 bg-white p-5 hover:border-emerald-300" href={href} key={href}><div className="flex items-center gap-2"><Icon aria-hidden className="size-5 text-emerald-700" /><h2 className="font-semibold">{title}</h2></div><p className="mt-3 flex-1 text-sm leading-6 text-zinc-600">{body}</p><span className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-emerald-700">{ro ? "Deschide" : "Открыть"}<ArrowRight aria-hidden className="size-4 transition-transform group-hover:translate-x-0.5" /></span></Link>)}</div></main>;
}
