import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { createFinalCustomerService, getFinalCustomerContext } from "@/src/modules/final-customer/server";
import { getFinalCustomerLocale } from "@/src/modules/final-customer/locale";
import { customerDate, customerMoney, orderStatus, paymentStatus } from "@/src/modules/final-customer/presentation";
import { OperationalStatusPair } from "@/src/modules/cabinet-experience/components";

export default async function FinalCustomerOrderPage({ params }: { params: Promise<{ orderId: string }> }) {
  const [{ orderId }, context, locale] = await Promise.all([params, getFinalCustomerContext(), getFinalCustomerLocale()]);
  const order = await createFinalCustomerService().orderDetail(context.account, orderId); if (!order) notFound(); const ro = locale === "ro";
  return <main className="mx-auto max-w-5xl space-y-5 px-4 py-6 sm:py-8">
    <header><Link className="inline-flex min-h-11 items-center text-sm font-semibold text-emerald-700" href="/account/orders">← {ro ? "Comenzi" : "Заказы"}</Link><div className="mt-1 flex flex-wrap items-end justify-between gap-3"><div><h1 className="font-mono text-2xl font-semibold">{order.number}</h1><p className="mt-1 text-sm text-zinc-500">{customerDate(order.createdAt, locale)}</p></div><strong className="text-xl tabular-nums">{customerMoney(order.total, order.currency, locale)}</strong></div></header>
    <section className="rounded-xl border border-zinc-200 bg-white p-5"><h2 className="mb-4 font-semibold">{ro ? "Starea curentă" : "Текущее состояние"}</h2><OperationalStatusPair primaryLabel={ro ? "Comandă" : "Заказ"} primaryValue={orderStatus(order.status, locale)} secondaryLabel={ro ? "Plată" : "Оплата"} secondaryValue={paymentStatus(order.paymentState, locale)} />{order.paidAt ? <p className="mt-3 text-xs text-zinc-500">{ro ? "Plată înregistrată" : "Оплата зарегистрирована"}: {customerDate(order.paidAt, locale)}</p> : null}</section>
    <section><h2 className="mb-3 font-semibold">{ro ? "Produse" : "Товары"}</h2><ul className="divide-y divide-zinc-200 overflow-hidden rounded-xl border border-zinc-200 bg-white">{order.lines.map((line) => <li className="grid gap-3 p-4 sm:grid-cols-[56px_minmax(0,1fr)_auto] sm:items-center" key={line.id}><div className="relative size-14 overflow-hidden rounded-lg bg-zinc-100">{line.imageUrl ? <Image alt="" fill className="object-contain p-1" sizes="56px" src={line.imageUrl} /> : null}</div><div className="min-w-0">{line.currentProduct ? <Link className="font-semibold hover:text-emerald-700" href={`/products/${line.currentProduct.slug}?lang=${locale}`}>{line.name}</Link> : <p className="font-semibold">{line.name}</p>}<p className="mt-1 text-xs text-zinc-500">SKU {line.sku} · {line.quantity} × {customerMoney(line.unitPrice, line.currency, locale)}</p></div><strong className="tabular-nums">{customerMoney(line.lineTotal, line.currency, locale)}</strong></li>)}</ul></section>
    <section className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-zinc-200 bg-white p-5"><h2 className="font-semibold">{ro ? "Plată" : "Оплата"}</h2><p className="mt-2 text-sm font-semibold text-emerald-700">{paymentStatus(order.paymentState, locale)}</p></div><div className="rounded-xl border border-zinc-200 bg-white p-5"><h2 className="font-semibold">{ro ? "Documente" : "Документы"}</h2><Link className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-emerald-700" href={`/account/documents?orderId=${order.id}`}>{ro ? "Documentele produselor" : "Документы по товарам"}</Link></div></section>
    {address(order.deliveryAddress) ? <section className="rounded-xl border border-zinc-200 bg-white p-5"><h2 className="font-semibold">{ro ? "Adresa din comandă" : "Адрес из заказа"}</h2><p className="mt-2 text-sm text-zinc-600">{address(order.deliveryAddress)}</p></section> : null}
    <section className="rounded-xl border border-zinc-200 bg-white p-5"><h2 className="font-semibold">{ro ? "Ajutor" : "Поддержка"}</h2><Link className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-emerald-700" href={`/account/service/new?orderId=${order.id}`}>{ro ? "Întrebare despre comandă" : "Задать вопрос по заказу"}</Link></section>
  </main>;
}
function address(value: Readonly<Record<string, unknown>>) { return [value.locality, value.street, value.building, value.unit].filter(Boolean).join(", "); }
