import { describe, expect, it, vi } from "vitest";
import { MembershipStatus } from "../../access-control/types";
import { PartnerSupportService } from "../service";
import { PartnerSupportRepositoryError, type PartnerSupportRepository } from "../repository";

function fixture() { const repository = { create: vi.fn().mockResolvedValue({ id: "ticket", ticketNumber: "SUP-2026-000001", status: "new", version: 1 }), listPartner: vi.fn().mockResolvedValue({ items: [], total: 0, page: 1 }), partnerTransition: vi.fn().mockResolvedValue({ id: "ticket", status: "resolved", version: 2 }), dashboard: vi.fn().mockResolvedValue([]) } as unknown as PartnerSupportRepository; const access = { getOwnMemberships: vi.fn().mockResolvedValue([{ companyId: "11111111-1111-1111-1111-111111111111", status: MembershipStatus.Active }]), getActiveCompanyContext: vi.fn().mockResolvedValue({ company: { id: "11111111-1111-1111-1111-111111111111" } }) }; return { repository, service: new PartnerSupportService(repository, access as never) }; }
describe("PartnerSupportService", () => {
  it("passes only the validated active company to creation", async () => { const { repository, service } = fixture(); await service.create("user", { description: "A sufficiently detailed support request.", priority: "high", idempotencyKey: "22222222-2222-2222-2222-222222222222", locale: "ru" }); expect(repository.create).toHaveBeenCalledWith(expect.objectContaining({ companyId: "11111111-1111-1111-1111-111111111111", priority: "high" })); });
  it("rejects short descriptions and partner-defined emergency priority", async () => { const { service } = fixture(); await expect(service.create("user", { description: "short", priority: "high", idempotencyKey: "22222222-2222-2222-2222-222222222222", locale: "ru" })).rejects.toThrow(/20/); await expect(service.create("user", { description: "A sufficiently detailed support request.", priority: "critical", idempotencyKey: "22222222-2222-2222-2222-222222222222", locale: "ru" })).rejects.toThrow(/приоритет/i); });
  it("denies suspended membership before repository access", async () => { const { repository, service } = fixture(); (service as unknown as { companyAccess: { getOwnMemberships: ReturnType<typeof vi.fn> } }).companyAccess.getOwnMemberships.mockResolvedValue([{ companyId: "company", status: MembershipStatus.Suspended }]); await expect(service.listPartner("user", {})).rejects.toThrow(/Активная компания/); expect(repository.listPartner).not.toHaveBeenCalled(); });
  it("allows only governed partner status actions", async () => { const { repository, service } = fixture(); await service.partnerTransition("user", { ticketId: "22222222-2222-2222-2222-222222222222", expectedVersion: 1, action: "confirm_solution" }); expect(repository.partnerTransition).toHaveBeenCalledWith(expect.objectContaining({ action: "confirm_solution" })); await expect(service.partnerTransition("user", { ticketId: "22222222-2222-2222-2222-222222222222", expectedVersion: 1, action: "close_anything" })).rejects.toThrow(/Недоступное действие/); });
  it("returns one stable conflict without retrying a stale transition", async () => { const { repository, service } = fixture(); vi.mocked(repository.partnerTransition).mockRejectedValue(new PartnerSupportRepositoryError("PT409")); await expect(service.partnerTransition("user", { ticketId: "22222222-2222-2222-2222-222222222222", expectedVersion: 1, action: "confirm_solution" })).rejects.toMatchObject({ code: "SUPPORT_TICKET_CONFLICT" }); expect(repository.partnerTransition).toHaveBeenCalledOnce(); });
});
