import { randomUUID } from "node:crypto";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getFinalCustomerContext } from "@/src/modules/final-customer/server";
import { getFinalCustomerLocale } from "@/src/modules/final-customer/locale";
import { publicPartnerLogoUrl } from "@/src/modules/public-retail/services/public-partner-directory.service";
import { selectInstallationPartnerAction, submitInstallationReviewAction, transitionCustomerInstallationAction } from "@/src/modules/installation-marketplace/actions";
import { getInstallationMarketplaceService } from "@/src/modules/installation-marketplace/server";
import { marketplaceCopy, needLabels, objectLabels, statusLabels } from "@/src/modules/installation-marketplace/copy";

export default async function CustomerInstallationDetailPage({params}:{params:Promise<{projectId:string}>}){
  const [{projectId},context,locale]=await Promise.all([params,getFinalCustomerContext(),getFinalCustomerLocale()]);
  const service=getInstallationMarketplaceService(); const project=await service.getCustomer(projectId,locale); if(!project)notFound();
  const shortlist=project.status==="DRAFT"||project.status==="PARTNER_DECLINED"?await service.shortlist(project.id,context.account.id,locale):[];
  const copy=marketplaceCopy[locale];
  return <main className="mx-auto max-w-5xl space-y-5 px-4 py-6 sm:py-8"><header><Link className="text-sm font-semibold text-emerald-700" href="/account/installations">← {copy.projects}</Link><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">{needLabels[locale][project.needType]}</h1><p className="mt-1 text-sm text-zinc-600">{objectLabels[locale][project.objectType]} · {project.locality}</p></div><span className="rounded-full bg-zinc-100 px-3 py-1 text-xs font-semibold">{statusLabels[locale][project.status]}</span></div></header>
    {project.items.length?<section className="rounded-xl border border-zinc-200 bg-white p-4"><h2 className="font-semibold">{locale==="ro"?"Echipamente":"Оборудование"}</h2><ul className="mt-3 grid gap-2">{project.items.map(item=><li className="flex items-center gap-3" key={item.id}>{item.imageUrl?<Image alt="" className="size-12 rounded-md object-contain" height={48} src={item.imageUrl} width={48}/>:<span className="size-12 rounded-md bg-zinc-100"/>}<div><p className="text-sm font-semibold">{item.name}</p><p className="text-xs text-zinc-500">SKU {item.sku} · {item.quantity}</p></div></li>)}</ul></section>:null}
    {project.assignment?<section className="rounded-xl border border-zinc-200 bg-white p-4"><h2 className="font-semibold">{project.assignment.partner.displayName}</h2><p className="mt-1 text-sm text-zinc-600">{project.assignment.partner.description}</p><RatingLine count={project.assignment.partner.verifiedReviewCount} locale={locale} rating={project.assignment.partner.averageVerifiedRating}/>{project.assignment.declineReason?<p className="mt-3 text-sm text-amber-800">{project.assignment.declineReason}</p>:null}</section>:null}
    {shortlist.length?<section><h2 className="text-xl font-semibold">{copy.selectPartner}</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{shortlist.map(partner=><article className="rounded-xl border border-zinc-200 bg-white p-4" key={partner.providerId}>{partner.recommended?<span className="mb-3 inline-flex rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-800">{copy.recommended}</span>:null}<div className="flex gap-3">{partner.logoPath?<Image alt="" className="size-12 rounded-md object-contain" height={48} src={publicPartnerLogoUrl(partner.logoPath)??""} width={48}/>:null}<div><h3 className="font-semibold">{partner.displayName}</h3><p className="text-xs text-zinc-500">{partner.coverage}</p></div></div><p className="mt-3 text-sm text-zinc-600">{partner.description}</p><RatingLine count={partner.verifiedReviewCount} locale={locale} rating={partner.averageVerifiedRating}/><p className="mt-1 text-xs text-zinc-500">{partner.completedVerifiedInstallations} {copy.verifiedInstallations}</p>{partner.learningState==="NEW_PARTNER"?<p className="mt-2 text-xs font-medium text-blue-700">{copy.newPartner}</p>:null}{partner.typicalResponse?<p className="mt-2 text-xs text-zinc-600">{partner.typicalResponse==="FAST"?copy.responseFast:partner.typicalResponse==="SAME_DAY"?copy.responseSameDay:copy.responseLonger}</p>:null}<form action={selectInstallationPartnerAction} className="mt-4"><input name="projectId" type="hidden" value={project.id}/><input name="providerId" type="hidden" value={partner.providerId}/><input name="revision" type="hidden" value={project.revision}/><input name="idempotencyKey" type="hidden" value={randomUUID()}/><button className="min-h-11 w-full rounded-lg bg-zinc-950 px-4 text-sm font-semibold text-white">{copy.choose}</button></form></article>)}</div></section>:null}
    {project.status==="INSTALLED"?<div className="grid gap-2 sm:grid-cols-2"><CustomerCommand command="CONFIRM" label={copy.confirm} projectId={project.id} revision={project.revision}/><CustomerCommand command="DISPUTE" label={copy.dispute} projectId={project.id} revision={project.revision} secondary/></div>:null}
    {!["INSTALLED","CUSTOMER_CONFIRMED","CLOSED","CANCELLED","DISPUTED"].includes(project.status)?<CustomerCommand command="CANCEL" label={copy.cancel} projectId={project.id} revision={project.revision} secondary/>:null}
    {project.status==="CUSTOMER_CONFIRMED"&&!project.review?<ReviewForm copy={copy} projectId={project.id}/>:null}
    {project.review?<section className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><h2 className="font-semibold">{copy.confirmedReview}</h2><p className="mt-2 text-sm">{"★".repeat(project.review.overallRating)} · {project.review.comment}</p><p className="mt-2 text-xs font-semibold text-emerald-800">VERIFIED_INSTALLATION</p></section>:null}
    <section className="rounded-xl border border-zinc-200 bg-white p-4"><h2 className="font-semibold">{locale==="ro"?"Cronologie":"Хронология"}</h2><ol className="mt-3 grid gap-2 text-sm text-zinc-600">{project.timeline.map(event=><li key={event.id}>{statusEvent(event.type,locale)}</li>)}</ol></section>
  </main>;
}

function CustomerCommand({command,label,projectId,revision,secondary=false}:{command:"CONFIRM"|"DISPUTE"|"CANCEL";label:string;projectId:string;revision:number;secondary?:boolean}){return <form action={transitionCustomerInstallationAction}><input name="projectId" type="hidden" value={projectId}/><input name="command" type="hidden" value={command}/><input name="revision" type="hidden" value={revision}/><input name="idempotencyKey" type="hidden" value={randomUUID()}/><button className={`min-h-11 w-full rounded-lg px-4 text-sm font-semibold ${secondary?"border border-zinc-300 bg-white":"bg-emerald-700 text-white"}`}>{label}</button></form>}
function RatingLine({rating,count,locale}:{rating:number|null;count:number;locale:"ru"|"ro"}){return <p className="mt-3 text-sm"><strong>{rating??"—"}</strong> · {count} {locale==="ro"?count===1?"recenzie verificată":"recenzii verificate":count===1?"подтверждённый отзыв":"подтверждённых отзывов"}</p>}
function ReviewForm({projectId,copy}:{projectId:string;copy:typeof marketplaceCopy.ru|typeof marketplaceCopy.ro}){return <form action={submitInstallationReviewAction} className="grid gap-3 rounded-xl border border-zinc-200 bg-white p-4"><h2 className="text-xl font-semibold">{copy.leaveReview}</h2><input name="projectId" type="hidden" value={projectId}/><input name="idempotencyKey" type="hidden" value={randomUUID()}/>{[["overall",copy.rating],["workmanship",copy.workmanship],["communication",copy.communication],["agreement",copy.agreement]].map(([name,label])=><label className="grid gap-1 text-sm font-medium" key={name}>{label}<select className="min-h-11 rounded-md border border-zinc-300 px-3" name={name}>{[5,4,3,2,1].map(value=><option key={value} value={value}>{value}</option>)}</select></label>)}<label className="grid gap-1 text-sm font-medium">{copy.comment}<textarea className="min-h-24 rounded-md border border-zinc-300 p-3" maxLength={1000} name="comment"/></label><button className="min-h-11 rounded-lg bg-zinc-950 px-4 text-sm font-semibold text-white">{copy.publishReview}</button></form>}
function statusEvent(type:string,locale:"ru"|"ro"){const text:Record<string,[string,string]>={PROJECT_CREATED:["Заявка создана","Cerere creată"],PARTNER_SELECTED:["Партнёр выбран","Partener selectat"],PARTNER_ACCEPTED:["Партнёр принял заявку","Partenerul a acceptat"],PARTNER_DECLINED:["Партнёр отказался","Partenerul a refuzat"],CONTACTED:["Партнёр связался","Partenerul a contactat"],SCHEDULED:["Монтаж запланирован","Instalare programată"],INSTALLED:["Партнёр отметил монтаж выполненным","Partenerul a declarat instalarea finalizată"],CUSTOMER_CONFIRMED:["Клиент подтвердил завершение","Clientul a confirmat finalizarea"],DISPUTED:["Клиент сообщил о проблеме","Clientul a raportat o problemă"],REVIEW_SUBMITTED:["Опубликован подтверждённый отзыв","Recenzie verificată publicată"]};return text[type]?.[locale==="ro"?1:0]??type}
