import Link from "next/link";
import { ArrowRight, Plus, QrCode } from "lucide-react";

import { createAgentCabinetService, referralStatusCopy } from "@/src/modules/agent-cabinet";
import { AgentPageHeader, primaryButton, secondaryButton } from "@/src/modules/agent-cabinet/components/PageHeader";
import { ReferralStatusBadge } from "@/src/modules/agent-cabinet/components/StatusBadge";

export default async function AgentHomePage() {
  const overview = await createAgentCabinetService().overview(); if (!overview) return null;
  const kpis = [["Мои клиенты", overview.kpis.myClients], ["Активные заявки", overview.kpis.activeReferrals], ["Новые заявки", overview.kpis.newReferrals], ["Закреплено за мной", overview.kpis.attributedToMe]] as const;
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-6 sm:py-8"><AgentPageHeader title="Обзор" actions={<><Link className={primaryButton} href="/agent/qr#referral-link"><Plus size={18}/>Добавить клиента</Link><Link className={secondaryButton} href="/agent/qr"><QrCode size={18}/>Показать мой QR</Link></>}/><section aria-label="Основные показатели" className="grid grid-cols-2 border-l border-t border-zinc-200 bg-white lg:grid-cols-4">{kpis.map(([label,value])=><div className="border-b border-r border-zinc-200 p-4" key={label}><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{value}</p></div>)}</section><div className="grid gap-5 lg:grid-cols-3"><OverviewList title="Требует внимания" empty="Сейчас всё в порядке." items={overview.needsAttention}/><OverviewList title="Последние заявки" empty="У вас пока нет заявок." items={overview.latestReferrals}/><section className="border border-zinc-200 bg-white"><h2 className="border-b border-zinc-200 px-4 py-3 font-semibold">Последние клиенты</h2>{overview.latestClients.length?<ul>{overview.latestClients.map(item=><li className="border-b border-zinc-100 last:border-0" key={item.id}><Link className="flex min-h-16 items-center justify-between gap-3 px-4 py-3 hover:bg-zinc-50" href={`/agent/clients/${item.id}`}><span><span className="block text-sm font-medium">{item.name}</span><span className="text-xs text-zinc-500">до {date(item.protectionUntil)}</span></span><ArrowRight size={16}/></Link></li>)}</ul>:<p className="p-4 text-sm text-zinc-500">После подтверждения первой заявки клиент появится здесь.</p>}</section></div></main>;
}
function OverviewList({title,empty,items}:{title:string;empty:string;items:Array<{id:string;name:string;status:keyof typeof referralStatusCopy;submittedAt:string}>}){return <section className="border border-zinc-200 bg-white"><h2 className="border-b border-zinc-200 px-4 py-3 font-semibold">{title}</h2>{items.length?<ul>{items.map(item=><li className="border-b border-zinc-100 last:border-0" key={item.id}><Link className="flex min-h-16 items-center justify-between gap-3 px-4 py-3 hover:bg-zinc-50" href={`/agent/referrals/${item.id}`}><span><span className="block text-sm font-medium">{item.name}</span><span className="text-xs text-zinc-500">{date(item.submittedAt)}</span></span><ReferralStatusBadge status={item.status}/></Link></li>)}</ul>:<p className="p-4 text-sm text-zinc-500">{empty}</p>}</section>}
function date(v:string){return new Intl.DateTimeFormat("ru-MD",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v))}
