import {
  publishInstallationTariffAction,
  reassignInstallationRequirementAction,
  saveInstallationProviderAction,
  saveInstallationTariffDraftAction,
  transitionAdminInstallationExecutionAction,
  simulateRetailOrderPaymentAction,
} from "@/src/modules/retail-marketplace/actions";
import { getRetailMarketplaceRepository } from "@/src/modules/retail-marketplace/server";
import type { InstallationAssignmentAdminReport } from "@/src/modules/retail-marketplace/types";
import { requireAdminPagePermission } from "@/src/modules/admin/services/admin-page-guard";

const lineLabels = {
  camera_installation: "Монтаж камеры",
  cable_laying: "Прокладка кабеля",
  commissioning: "Пусконаладка",
  remote_configuration: "Настройка удалённого просмотра",
} as const;
const executionViews = [
  { key: "all", label: "Все" }, { key: "scheduled", label: "Запланировано" }, { key: "in_progress", label: "В работе" },
  { key: "confirmation", label: "Ожидает заказчика" }, { key: "issues", label: "Проблемы и споры" }, { key: "completed", label: "Завершено" },
] as const;

export default async function RetailInstallationAdminPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdminPagePermission("admin.retail_marketplace.view");
  const [report, assignments, query] = await Promise.all([getRetailMarketplaceRepository().getAdminReport(), getRetailMarketplaceRepository().getAssignmentAdminReport(), searchParams]);
  const draft = report.tariffSets.find((set) => set.status === "draft");
  const published = report.tariffSets.find((set) => set.status === "published");
  const executionView = executionViews.some((view) => view.key === query.executionView) ? String(query.executionView) : "all";
  const filteredRequirements = assignments.requirements.filter((requirement) => executionView === "all" || executionView === "scheduled" && requirement.execution?.state === "scheduled" || executionView === "in_progress" && requirement.execution?.state === "in_progress" || executionView === "confirmation" && requirement.execution?.state === "customer_confirmation_pending" || executionView === "issues" && ["issue_reported", "disputed"].includes(requirement.execution?.state ?? "") || executionView === "completed" && ["customer_confirmed", "resolved", "cancelled"].includes(requirement.execution?.state ?? ""));
  return <main className="space-y-8">
    <header><p className="text-sm font-semibold text-emerald-700">Retail Marketplace</p><h1 className="mt-1 text-2xl font-semibold">Монтаж: тарифы и исполнители</h1><p className="mt-2 max-w-3xl text-sm text-zinc-600">Тарифы Novotech и допуск исполнителей. Назначение заказов и выплаты в этот раздел не входят.</p></header>
    {query.saved ? <p className="border-l-4 border-emerald-600 bg-emerald-50 p-3 text-sm">Изменение сохранено.</p> : null}
    <section className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Тарифы CCTV</h2><p className="text-sm text-zinc-600">Опубликованная версия: {published ? `v${published.version}` : "нет"}</p></div></div>
      <form action={saveInstallationTariffDraftAction} className="grid gap-4 border border-zinc-200 bg-white p-4 md:grid-cols-2 xl:grid-cols-4">
        <input name="tariffSetId" type="hidden" value={draft?.id ?? ""} /><input name="revision" type="hidden" value={draft?.revision ?? 0} />
        {Object.entries(lineLabels).map(([key,label]) => <label className="grid gap-1 text-sm" key={key}><span className="font-medium">{label}, MDL</span><input className="min-h-11 border border-zinc-300 px-3" defaultValue={draft?.lines.find((line) => line.serviceType === key)?.unitPrice ?? ""} min="0" name={key} required step="0.01" type="number" /></label>)}
        <label className="grid gap-1 text-sm"><span className="font-medium">Действует с</span><input className="min-h-11 border border-zinc-300 px-3" defaultValue={dateTimeValue(draft?.effectiveFrom)} name="effectiveFrom" required type="datetime-local" /></label>
        <label className="grid gap-1 text-sm"><span className="font-medium">НДС</span><select className="min-h-11 border border-zinc-300 px-3" defaultValue={draft?.vatTreatment ?? "not_specified"} name="vatTreatment"><option value="included">Включён</option><option value="excluded">Не включён</option><option value="not_specified">Не указан</option></select></label>
        <label className="grid gap-1 text-sm md:col-span-2"><span className="font-medium">Причина изменения</span><input className="min-h-11 border border-zinc-300 px-3" minLength={5} name="reason" required /></label>
        <button className="min-h-11 bg-zinc-900 px-4 text-sm font-semibold text-white" type="submit">{draft ? "Сохранить черновик" : "Создать черновик"}</button>
      </form>
      {draft && draft.lines.length === 4 ? <form action={publishInstallationTariffAction} className="flex flex-wrap gap-3 border border-amber-200 bg-amber-50 p-4"><input name="tariffSetId" type="hidden" value={draft.id} /><input name="revision" type="hidden" value={draft.revision} /><input className="min-h-11 flex-1 border border-zinc-300 px-3" minLength={5} name="reason" placeholder="Причина публикации" required /><button className="min-h-11 bg-emerald-700 px-4 text-sm font-semibold text-white" type="submit">Опубликовать v{draft.version}</button></form> : null}
    </section>
    <section className="space-y-4"><div><h2 className="text-xl font-semibold">Исполнители</h2><p className="text-sm text-zinc-600">Публичность требует активного статуса, одобрения, участия, опубликованного профиля, CCTV и региона.</p></div>
      <details className="border border-zinc-200 bg-white p-4"><summary className="min-h-11 cursor-pointer font-semibold">Добавить партнёра-исполнителя</summary><form action={saveInstallationProviderAction} className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <input name="providerId" type="hidden" value="" /><input name="revision" type="hidden" value="0" /><input name="providerType" type="hidden" value="partner_company" />
        <label className="grid gap-1 text-sm"><span className="font-medium">Партнёрская компания</span><select className="min-h-11 border border-zinc-300 px-3" name="backingId" required>{report.partnerCompanies.map((company)=><option key={company.id} value={company.id}>{company.name}</option>)}</select></label>
        <Field defaultValue="" label="Публичное имя RU" name="publicNameRu" /><Field defaultValue="" label="Публичное имя RO" name="publicNameRo" />
        <input name="operationalStatus" type="hidden" value="inactive" /><input name="approvalStatus" type="hidden" value="pending" /><input name="publicProfileStatus" type="hidden" value="draft" /><input name="availability" type="hidden" value="unavailable" /><input name="acceptanceSlaMinutes" type="hidden" value="120" />
        <label className="flex min-h-11 items-center gap-2 text-sm"><input name="cctv" type="checkbox" /> Компетенция CCTV</label><fieldset className="md:col-span-2"><legend className="text-sm font-medium">Регионы</legend><div className="mt-2 flex flex-wrap gap-4">{report.regions.map((region)=><label className="flex min-h-11 items-center gap-2 text-sm" key={region.id}><input name="regions" type="checkbox" value={region.code} />{region.nameRu}</label>)}</div></fieldset>
        <label className="grid gap-1 text-sm md:col-span-2"><span className="font-medium">Причина создания</span><input className="min-h-11 border border-zinc-300 px-3" minLength={5} name="reason" required /></label><button className="min-h-11 bg-zinc-900 px-4 text-sm font-semibold text-white" type="submit">Создать черновик</button>
      </form></details>
      <div className="grid gap-4">{report.providers.map((provider) => <form action={saveInstallationProviderAction} className="grid gap-4 border border-zinc-200 bg-white p-4 md:grid-cols-2 xl:grid-cols-4" key={provider.id}>
        <input name="providerId" type="hidden" value={provider.id} /><input name="providerType" type="hidden" value={provider.providerType} /><input name="backingId" type="hidden" value={(provider.providerType === "partner_company" ? report.partnerCompanies : report.internalTeams).find((entry) => entry.name === provider.backingName)?.id ?? ""} /><input name="revision" type="hidden" value={provider.revision} />
        <div className="md:col-span-2 xl:col-span-4"><h3 className="font-semibold">{provider.backingName}</h3><p className="text-xs text-zinc-500">{provider.providerType === "internal_team" ? "Команда Novotech" : "Партнёрская компания"}</p></div>
        <Field defaultValue={provider.publicNameRu} label="Публичное имя RU" name="publicNameRu" /><Field defaultValue={provider.publicNameRo} label="Публичное имя RO" name="publicNameRo" />
        <Select defaultValue={provider.operationalStatus} label="Рабочий статус" name="operationalStatus" options={["active","inactive","suspended"]} /><Select defaultValue={provider.approvalStatus} label="Одобрение" name="approvalStatus" options={["pending","approved","rejected"]} />
        <Select defaultValue={provider.publicProfileStatus} label="Публичный профиль" name="publicProfileStatus" options={["draft","published"]} /><Select defaultValue={provider.availability} label="Доступность" name="availability" options={["available","limited","unavailable"]} />
        <Field defaultValue={String(provider.acceptanceSlaMinutes)} label="SLA ответа, минут" name="acceptanceSlaMinutes" type="number" /><Field defaultValue={provider.maxConcurrentJobs?.toString() ?? ""} label="Одновременных работ" name="maxConcurrentJobs" type="number" />
        <label className="flex min-h-11 items-center gap-2 text-sm"><input defaultChecked={provider.marketplaceEnabled} name="marketplaceEnabled" type="checkbox" /> Участие включено</label><label className="flex min-h-11 items-center gap-2 text-sm"><input defaultChecked={provider.competencies.includes("cctv")} name="cctv" type="checkbox" /> Компетенция CCTV</label>
        <fieldset className="md:col-span-2"><legend className="text-sm font-medium">Регионы</legend><div className="mt-2 flex flex-wrap gap-4">{report.regions.map((region) => <label className="flex min-h-11 items-center gap-2 text-sm" key={region.id}><input defaultChecked={provider.regions.includes(region.code)} name="regions" type="checkbox" value={region.code} />{region.nameRu}</label>)}</div></fieldset>
        <label className="grid gap-1 text-sm md:col-span-2"><span className="font-medium">Причина изменения</span><input className="min-h-11 border border-zinc-300 px-3" minLength={5} name="reason" required /></label><button className="min-h-11 bg-zinc-900 px-4 text-sm font-semibold text-white" type="submit">Сохранить исполнителя</button>
      </form>)}</div>
    </section>
    <section className="space-y-4" aria-labelledby="assignment-operations-title">
      <div><h2 className="text-xl font-semibold" id="assignment-operations-title">Назначение монтажных заказов</h2><p className="text-sm text-zinc-600">Назначение начинается только после подтверждённой оплаты. Симулятор использует тот же нейтральный путь активации, что и будущий платёжный адаптер.</p></div>
      <details className="border border-zinc-200 bg-white p-4"><summary className="min-h-11 cursor-pointer font-semibold">Симулировать подтверждение оплаты</summary><form action={simulateRetailOrderPaymentAction} className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <Field defaultValue="" label="RetailOrder ID" name="retailOrderId"/>
        <input name="idempotencyKey" type="hidden" value={crypto.randomUUID()}/><label className="grid gap-1 text-sm md:col-span-2"><span className="font-medium">Причина контролируемой симуляции</span><input className="min-h-11 border border-zinc-300 px-3" minLength={10} name="reason" required/></label><button className="min-h-11 bg-zinc-900 px-4 text-sm font-semibold text-white" type="submit">Подтвердить тестовую оплату</button>
      </form></details>
      <nav aria-label="Состояние исполнения" className="flex flex-wrap gap-2">{executionViews.map((view)=><a aria-current={executionView===view.key ? "page" : undefined} className={`inline-flex min-h-11 items-center border px-3 text-sm font-semibold ${executionView===view.key ? "border-zinc-900 bg-zinc-900 text-white" : "border-zinc-300 bg-white"}`} href={`/admin/retail/installation?executionView=${view.key}`} key={view.key}>{view.label}</a>)}</nav>
      <div className="grid gap-3">{filteredRequirements.length ? filteredRequirements.map((requirement)=><article className="border border-zinc-200 bg-white p-4" key={requirement.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{requirement.orderNumber} · {requirement.locality}</h3><p className="text-sm text-zinc-600">{requirement.execution ? `${executionLabel(requirement.execution.state)} · ` : ""}{requirement.customerInstallationCharge} {requirement.currency} · {requirement.selectionMode}</p>{requirement.execution?.scheduledStartAt ? <p className="mt-1 text-sm">{new Intl.DateTimeFormat("ru-MD", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Chisinau" }).format(new Date(requirement.execution.scheduledStartAt))}</p> : null}</div><span className="rounded bg-zinc-100 px-2 py-1 text-xs font-semibold">{requirement.attempts.length} попыток</span></div>
        <ol className="mt-3 grid gap-2 text-sm">{requirement.attempts.map((attempt)=><li className="flex flex-wrap justify-between gap-2 border-t border-zinc-100 pt-2" key={attempt.id}><span>#{attempt.ordinal} · {report.providers.find((provider)=>provider.id===attempt.providerId)?.backingName ?? "Исполнитель"}</span><span>{attempt.status} · {attempt.source}</span></li>)}</ol>
        {requirement.status !== "assigned" ? <form action={reassignInstallationRequirementAction} className="mt-4 grid gap-2 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]"><input name="requirementId" type="hidden" value={requirement.id}/><input name="revision" type="hidden" value={requirement.revision}/><select aria-label="Исполнитель" className="min-h-11 border border-zinc-300 px-3" name="providerId" required>{report.providers.map((provider)=><option key={provider.id} value={provider.id}>{provider.backingName}</option>)}</select><input aria-label="Причина переназначения" className="min-h-11 border border-zinc-300 px-3" minLength={10} name="reason" placeholder="Причина переназначения" required/><button className="min-h-11 border border-zinc-900 px-4 text-sm font-semibold">Переназначить</button></form> : null}
        {requirement.execution ? <AdminExecutionActions execution={requirement.execution}/> : null}
      </article>) : <p className="border border-zinc-200 bg-white p-4 text-sm text-zinc-600">Активированных монтажных требований пока нет.</p>}</div>
    </section>
  </main>;
}

function Field({ defaultValue,label,name,type="text" }: { defaultValue:string;label:string;name:string;type?:string }) { return <label className="grid gap-1 text-sm"><span className="font-medium">{label}</span><input className="min-h-11 border border-zinc-300 px-3" defaultValue={defaultValue} name={name} required={name !== "maxConcurrentJobs"} type={type} /></label>; }
function Select({ defaultValue,label,name,options }: { defaultValue:string;label:string;name:string;options:string[] }) { return <label className="grid gap-1 text-sm"><span className="font-medium">{label}</span><select className="min-h-11 border border-zinc-300 px-3" defaultValue={defaultValue} name={name}>{options.map((option)=><option key={option}>{option}</option>)}</select></label>; }
function dateTimeValue(value?: string) { const date=value ? new Date(value) : new Date(); return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16); }
function executionLabel(state: string) { return ({ scheduling: "Назначение даты", scheduled: "Запланировано", in_progress: "В работе", completed_by_provider: "Завершено исполнителем", customer_confirmation_pending: "Ожидает заказчика", customer_confirmed: "Подтверждено", issue_reported: "Есть проблема", disputed: "Спор", resolved: "Решено", cancelled: "Отменено" } as Record<string,string>)[state] ?? state; }
function AdminExecutionActions({ execution }: { execution: NonNullable<InstallationAssignmentAdminReport["requirements"][number]["execution"]> }) {
  const common = <><input name="executionId" type="hidden" value={execution.id}/><input name="revision" type="hidden" value={execution.revision}/><input name="idempotencyKey" type="hidden" value={crypto.randomUUID()}/></>;
  if (execution.state === "scheduling" || execution.state === "scheduled") return <div><form action={transitionAdminInstallationExecutionAction} className="mt-4 grid gap-2 md:grid-cols-4">{common}<input name="command" type="hidden" value="schedule"/><input aria-label="Дата монтажа" className="min-h-11 border border-zinc-300 px-3" name="scheduledStartAt" required type="datetime-local"/><input aria-label="Конец окна" className="min-h-11 border border-zinc-300 px-3" name="scheduledEndAt" type="datetime-local"/><input aria-label="Примечание" className="min-h-11 border border-zinc-300 px-3" maxLength={500} name="note"/><button className="min-h-11 border border-zinc-900 px-4 text-sm font-semibold">{execution.state === "scheduled" ? "Перенести" : "Запланировать"}</button></form>{execution.state === "scheduled" ? <form action={transitionAdminInstallationExecutionAction} className="mt-2"><input name="executionId" type="hidden" value={execution.id}/><input name="revision" type="hidden" value={execution.revision}/><input name="idempotencyKey" type="hidden" value={crypto.randomUUID()}/><input name="command" type="hidden" value="start"/><button className="min-h-11 bg-emerald-700 px-4 text-sm font-semibold text-white">Начать работы</button></form> : null}</div>;
  if (execution.state === "in_progress") return <form action={transitionAdminInstallationExecutionAction} className="mt-4 flex flex-wrap gap-2">{common}<input name="command" type="hidden" value="complete"/><input className="min-h-11 flex-1 border border-zinc-300 px-3" maxLength={500} name="note" placeholder="Примечание, необязательно"/><button className="min-h-11 bg-emerald-700 px-4 text-sm font-semibold text-white">Завершить работы</button></form>;
  if (execution.state === "issue_reported") return <div className="mt-4 flex flex-wrap gap-2"><form action={transitionAdminInstallationExecutionAction}>{common}<input name="command" type="hidden" value="open_dispute"/><button className="min-h-11 border border-amber-700 px-4 text-sm font-semibold text-amber-800">Открыть рассмотрение</button></form><ResolutionForm execution={execution}/></div>;
  if (execution.state === "disputed") return <ResolutionForm execution={execution}/>;
  return null;
}
function ResolutionForm({ execution }: { execution: NonNullable<InstallationAssignmentAdminReport["requirements"][number]["execution"]> }) { return <form action={transitionAdminInstallationExecutionAction} className="flex flex-wrap gap-2"><input name="executionId" type="hidden" value={execution.id}/><input name="revision" type="hidden" value={execution.revision}/><input name="idempotencyKey" type="hidden" value={crypto.randomUUID()}/><input name="command" type="hidden" value="resolve_dispute"/><input className="min-h-11 flex-1 border border-zinc-300 px-3" maxLength={500} minLength={3} name="note" placeholder="Результат рассмотрения" required/><button className="min-h-11 bg-emerald-700 px-4 text-sm font-semibold text-white">Закрыть обращение</button></form>; }
