"use server";
import {createHash,randomUUID} from "node:crypto";
import {revalidatePath} from "next/cache";
import {createAdminClient} from "@/src/lib/supabase/admin";
import {requireAdminPermission} from "../admin/services";
import {failureFromError,invalidInput,success,type ActionResult} from "../access-control/actions/action-result";
import {hasValidFileSignature,SERVICE_ATTACHMENT_MAX_BYTES} from "./attachment-policy";
import {SERVICE_DOCUMENT_TYPES,type ServiceDocumentType} from "./types";
export async function uploadServiceDocumentAction(_state:ActionResult<{id:string}>|null,formData:FormData):Promise<ActionResult<{id:string}>>{await requireAdminPermission("admin.service.manage");const file=formData.get("file");if(!(file instanceof File)||file.type!=="application/pdf"||file.size<1||file.size>SERVICE_ATTACHMENT_MAX_BYTES)return invalidInput("Выберите PDF-файл до 15 МБ.");const documentType=text(formData,"documentType") as ServiceDocumentType;if(!SERVICE_DOCUMENT_TYPES.includes(documentType))return invalidInput("Выберите тип документа.");const bytes=new Uint8Array(await file.arrayBuffer());if(!hasValidFileSignature(bytes,file.type))return invalidInput("Содержимое файла не соответствует PDF.");const documentId=randomUUID(),checksum=createHash("sha256").update(bytes).digest("hex"),storageKey=`service/${documentId}/${checksum}.pdf`,admin=createAdminClient();try{const{error:uploadError}=await admin.storage.from("partner-documents").upload(storageKey,bytes,{contentType:"application/pdf",upsert:false});if(uploadError)throw uploadError;const{data,error}=await admin.rpc("register_service_document",{p_document_id:documentId,p_case_id:text(formData,"caseId"),p_title:text(formData,"title"),p_service_document_type:documentType,p_issue_date:text(formData,"issueDate")||null,p_version:text(formData,"version")||"1",p_file_name:safeName(file.name),p_file_size:file.size,p_storage_key:storageKey,p_checksum:checksum,p_partner_visible:formData.get("partnerVisible")==="on"});if(error||typeof data!=="string")throw error??new Error("SERVICE_DOCUMENT_REGISTER_FAILED");if(data!==documentId)await admin.storage.from("partner-documents").remove([storageKey]);const caseId=text(formData,"caseId");revalidatePath(`/admin/service/${caseId}`);revalidatePath(`/cabinet/service/${caseId}`);revalidatePath("/cabinet/documents");return success("Сервисный документ добавлен.",{id:data})}catch(error){await admin.storage.from("partner-documents").remove([storageKey]);console.error({event:"service_document_upload_failed",caseId:text(formData,"caseId"),documentType,errorType:error instanceof Error?error.name:typeof error});return failureFromError(error)}}
function text(data:FormData,key:string){const value=data.get(key);return typeof value==="string"?value.trim():""}
function safeName(value:string){const clean=value.normalize("NFKC").replace(/[\r\n"\\/]/g,"_").trim().slice(0,180);return clean.toLowerCase().endsWith(".pdf")?clean:`${clean||"service-document"}.pdf`}
