import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound } from "next/navigation";

import { getPartnerWorkspaceContextAction } from "@/src/modules/partner-cabinet/actions";
import { getExternalPricesCopy } from "@/src/modules/partner-locale";
import { getPartnerLocale } from "@/src/modules/partner-locale/server";
import { ExternalPriceRepository, ExternalPriceService } from "@/src/modules/external-prices";
import { applyExternalPriceUploadAction, archiveExternalPriceUploadAction, confirmExternalPriceMappingAction, correctExternalPriceUploadAction, reviewExternalPriceRowAction } from "@/src/modules/external-prices/actions";

type Row={id:string;sheet:string;row:number;sourceCode:string|null;sourceName:string;normalizedModel:string|null;description:string|null;partnerPrice:number|null;retailPrice:number|null;currency:string;marker:string|null;catalogProductId:string|null;matchMethod:string;matchStatus:string;suggestedProducts:Array<{id:string;sku:string;name:string}>};
type Detail={id:string;sourceName:string;originalFilename:string;effectiveDate:string|null;currency:string;priceSchema:string;snapshotScope:string;status:string;detectedMapping:Record<string,unknown>|null;confirmedMapping:Record<string,unknown>|null;sheetNames:string[];totalRows:number;candidateRows:number;matchedRows:number;reviewRows:number;unmatchedRows:number;ignoredRows:number;markerRows:number;safeErrorCode:string|null;createdAt:string;appliedAt:string|null;rows:Row[]};

export default async function ExternalPriceImportPage({params}:{params:Promise<{uploadId:string}>}){
  const [{uploadId},contextResult,locale]=await Promise.all([params,getPartnerWorkspaceContextAction(),getPartnerLocale()]);
  if(!contextResult.success)throw new Error(contextResult.errorCode);
  const companyId=new ExternalPriceService().assertCompanyContext(contextResult.data);
  const raw=await new ExternalPriceRepository().getUpload(companyId,uploadId); if(!raw)notFound();
  const detail=raw as unknown as Detail, copy=getExternalPricesCopy(locale);
  return <main className="space-y-6"><header><Link className="text-sm font-semibold text-emerald-700" href="/cabinet/competitor-prices">← {copy.imports}</Link><h1 className="mt-3 text-2xl font-semibold">{detail.sourceName} · {detail.effectiveDate??detail.originalFilename}</h1><p className="mt-1 text-sm text-zinc-500">{copy.status}: {statusLabel(copy,detail.status)}</p></header>
    <section className="grid grid-cols-2 gap-px border border-zinc-200 bg-zinc-200 sm:grid-cols-3 lg:grid-cols-6">{metrics(copy,detail).map(({label,value})=><div className="bg-white p-3" key={label}><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</section>
    {detail.status==="mapping_required"||detail.status==="ready_for_review"?<MappingForm copy={copy} detail={detail}/>:null}
    {detail.status==="uploaded"||detail.status==="analyzing"?<p className="border-y border-zinc-200 py-5 text-sm text-zinc-600" role="status">{copy.analyzing}</p>:null}
    {detail.status==="failed"?<p className="border border-red-200 bg-red-50 p-4 text-sm text-red-800" role="alert">{copy.failed}: {detail.safeErrorCode??"ANALYSIS_FAILED"}</p>:null}
    {detail.status==="ready_for_review"||detail.status==="applied"?<ReviewTable copy={copy} detail={detail}/>:null}
    {detail.status==="applied"?<CorrectionForm copy={copy} detail={detail}/>:null}
    <div className="flex flex-wrap gap-3">{detail.status==="ready_for_review"?<form action={applyExternalPriceUploadAction}><input name="uploadId" type="hidden" value={detail.id}/><button className="min-h-11 bg-zinc-950 px-5 text-sm font-semibold text-white disabled:opacity-50" disabled={detail.reviewRows>0}>{copy.apply}</button></form>:null}{detail.status!=="archived"?<form action={archiveExternalPriceUploadAction}><input name="uploadId" type="hidden" value={detail.id}/><button className="min-h-11 border border-zinc-300 px-5 text-sm font-semibold">{copy.archive}</button></form>:null}</div>
  </main>;
}

function CorrectionForm({copy,detail}:{copy:ReturnType<typeof getExternalPricesCopy>;detail:Detail}){const map=detail.confirmedMapping??{};return <details className="border-y border-zinc-200 py-4"><summary className="cursor-pointer text-sm font-semibold">{copy.correctImport}</summary><form action={correctExternalPriceUploadAction} className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><input name="uploadId" type="hidden" value={detail.id}/><input name="correlationId" type="hidden" value={randomUUID()}/>{[{label:copy.productCode,name:"productCode"},{label:copy.productName,name:"productName"},{label:copy.description,name:"description"},{label:copy.partnerPriceColumn,name:"partnerPrice"},{label:copy.retailPriceColumn,name:"retailPrice"}].map(field=><label className="text-sm font-medium" key={field.name}>{field.label}<input className="mt-1 min-h-11 w-full border border-zinc-300 px-3 uppercase" defaultValue={typeof map[field.name]==="string"?String(map[field.name]):""} name={field.name} required={field.name==="productName"}/></label>)}<label className="text-sm font-medium">{copy.priceType}<select className="mt-1 min-h-11 w-full border border-zinc-300 px-3" defaultValue={detail.priceSchema} name="priceSchema"><option value="partner">{copy.partnerPrice}</option><option value="retail">{copy.retailPrice}</option><option value="both">{copy.bothPrices}</option><option value="detect">{copy.detect}</option></select></label><label className="text-sm font-medium">{copy.status}<select className="mt-1 min-h-11 w-full border border-zinc-300 px-3" defaultValue={detail.snapshotScope} name="snapshotScope"><option value="full">{copy.fullSnapshot}</option><option value="partial">{copy.partialUpdate}</option></select></label><label className="text-sm font-medium sm:col-span-2 lg:col-span-3">{copy.correctionReason}<input className="mt-1 min-h-11 w-full border border-zinc-300 px-3" minLength={10} name="reason" placeholder={copy.correctionReasonPlaceholder} required/></label><div className="sm:col-span-2 lg:col-span-5"><button className="min-h-11 bg-zinc-950 px-5 text-sm font-semibold text-white">{copy.startCorrection}</button></div></form></details>}

function MappingForm({copy,detail}:{copy:ReturnType<typeof getExternalPricesCopy>;detail:Detail}){const map=detail.confirmedMapping??detail.detectedMapping??{};const fields:Array<{label:string;name:string;value:unknown}>=[{label:copy.productCode,name:"productCode",value:map.productCode},{label:copy.productName,name:"productName",value:map.productName},{label:copy.description,name:"description",value:map.description},{label:copy.partnerPriceColumn,name:"partnerPrice",value:map.partnerPrice},{label:copy.retailPriceColumn,name:"retailPrice",value:map.retailPrice}];return <form action={confirmExternalPriceMappingAction} className="grid gap-4 border-y border-zinc-200 py-5 sm:grid-cols-2 lg:grid-cols-5"><input name="uploadId" type="hidden" value={detail.id}/>{fields.map(({label,name,value})=><label className="space-y-1 text-sm font-medium" key={name}>{label}<input className="mt-1 min-h-11 w-full border border-zinc-300 px-3 uppercase" defaultValue={typeof value==="string"?value:""} name={name} required={name==="productName"}/></label>)}<label className="flex min-h-11 items-center gap-2 text-sm sm:col-span-2"><input name="saveTemplate" type="checkbox"/>{copy.saveTemplate}</label><div className="sm:col-span-2 lg:col-span-3"><button className="min-h-11 bg-zinc-950 px-5 text-sm font-semibold text-white">{copy.confirmMapping}</button></div></form>;}

function ReviewTable({copy,detail}:{copy:ReturnType<typeof getExternalPricesCopy>;detail:Detail}){return <section><h2 className="text-base font-semibold">{copy.rows}</h2><div className="mt-3 space-y-2">{detail.rows.map(row=><article className="grid gap-3 border border-zinc-200 p-3 text-sm lg:grid-cols-[minmax(0,2fr)_1fr_1fr_minmax(0,2fr)] lg:items-center" key={row.id}><div><p className="font-semibold">{row.sourceName}</p><p className="text-xs text-zinc-500">{row.sheet} · {row.row} · {row.normalizedModel}{row.marker?` · ${row.marker}`:""}</p></div><p>{copy.partnerPrice}: {money(row.partnerPrice,row.currency)}</p><p>{copy.retailPrice}: {money(row.retailPrice,row.currency)}</p><div>{row.matchStatus==="needs_review"||row.matchStatus==="unmatched"?<form action={reviewExternalPriceRowAction} className="flex flex-wrap items-center gap-2"><input name="uploadId" type="hidden" value={detail.id}/><input name="rowId" type="hidden" value={row.id}/>{row.suggestedProducts.length?<select className="min-h-11 min-w-0 flex-1 border border-zinc-300 px-2" name="productId" required>{row.suggestedProducts.map(product=><option key={product.id} value={product.id}>{product.sku} · {product.name}</option>)}</select>:<span className="text-xs text-zinc-500">{copy.none}</span>} {row.suggestedProducts.length?<button className="min-h-11 border border-emerald-700 px-3 font-semibold text-emerald-800" name="decision" value="match">{copy.confirmMatch}</button>:null}<button className="min-h-11 border border-zinc-300 px-3 font-semibold" name="decision" value="skip">{copy.skip}</button></form>:<span className="font-semibold text-emerald-700">{copy.matched}</span>}</div></article>)}</div></section>;}
function money(value:number|null,currency:string){return value===null?"—":`${new Intl.NumberFormat("ru-MD",{minimumFractionDigits:2,maximumFractionDigits:4}).format(value)} ${currency}`;}
function statusLabel(copy:ReturnType<typeof getExternalPricesCopy>,status:string){return (copy as Record<string,string>)[status]??status;}
function metrics(copy:ReturnType<typeof getExternalPricesCopy>,detail:Detail):Array<{label:string;value:number}>{return[{label:copy.totalRows,value:detail.totalRows},{label:copy.dahuaCandidates,value:detail.candidateRows},{label:copy.matched,value:detail.matchedRows},{label:copy.review,value:detail.reviewRows},{label:copy.unmatched,value:detail.unmatchedRows},{label:copy.ignored,value:detail.ignoredRows}];}
