import "server-only";
import { createAdminClient } from "../../../lib/supabase/admin";
import type { StockBalanceKind, StockBalanceProvider, StockStageRow, StockWarehouseRow } from "../providers/one-c";

export type StockSyncStatus="never_run"|"queued"|"running"|"succeeded"|"failed";
export type StockSyncStage="warehouse_scan"|"physical_scan"|"reserved_scan"|"incoming_scan"|"stock_publication"|"completed";
export type StockSyncState={status:StockSyncStatus;activeSyncId:string|null;lastFailedSyncId:string|null;snapshotTime:string|null;currentStage:StockSyncStage|null;nextSkip:number;pageSize:number;pagesProcessed:number;physicalRows:number;reservedRows:number;incomingRows:number;warehousesLoaded:number;productsMatched:number;productsUnmatched:number;rowsPublished:number;rowsDeactivated:number;scanComplete:boolean;startedAt:string|null;lastSuccessfulSyncAt:string|null;errorCategory:string|null;failedStage:string|null;safeError:string|null;failedPage:number|null;updatedAt:string};
export interface StockSyncStore {start():Promise<{state:StockSyncState;started:boolean}>;getState():Promise<StockSyncState>;claim(syncId:string,token:string):Promise<boolean>;release(syncId:string,token:string):Promise<void>;stageWarehouses(syncId:string,rows:StockWarehouseRow[]):Promise<number>;stageBalances(syncId:string,kind:StockBalanceKind,rows:StockStageRow[]):Promise<number>;checkpoint(syncId:string,input:{stage:StockSyncStage;nextSkip:number;received:number;kind:StockBalanceKind|"warehouses";complete?:boolean}):Promise<void>;publish(syncId:string):Promise<void>;fail(syncId:string,stage:StockSyncStage,page:number,error:unknown):Promise<void>;failLaunch(syncId:string,message:string):Promise<void>}
const PAGE_SIZE=500,MAX_PAGES=5,BUDGET=45_000;

export class ChunkedStockSyncService{
 constructor(private provider:StockBalanceProvider,private store:StockSyncStore,private now:()=>number=Date.now){}
 start(){return this.store.start();} getState(){return this.store.getState();} failLaunch(id:string,message:string){return this.store.failLaunch(id,message);}
 async continue(syncId:string){let state=await this.store.getState();if(state.activeSyncId!==syncId||!["queued","running"].includes(state.status))return{state,pages:0};const token=crypto.randomUUID();if(!await this.store.claim(syncId,token))return{state:await this.store.getState(),pages:0};const start=this.now();let pages=0;try{while(pages<MAX_PAGES&&this.now()-start<BUDGET){state=await this.store.getState();const stage=state.currentStage;if(!stage||stage==="completed"||stage==="stock_publication")break;const page=stage==="warehouse_scan"?await this.provider.fetchWarehouses(state.nextSkip,state.pageSize):await this.provider.fetchBalances(kindFor(stage),state.snapshotTime!,state.nextSkip,state.pageSize);const received=page.rowCount;const staged=stage==="warehouse_scan"?await this.store.stageWarehouses(syncId,page.items as StockWarehouseRow[]):await this.store.stageBalances(syncId,kindFor(stage),page.items as StockStageRow[]);void staged;pages++;const complete=received<state.pageSize;const next=complete?nextStage(stage):stage;await this.store.checkpoint(syncId,{stage:next,nextSkip:complete?0:state.nextSkip+state.pageSize,received,kind:stage==="warehouse_scan"?"warehouses":kindFor(stage),complete:stage==="incoming_scan"&&complete});if(stage==="incoming_scan"&&complete){await this.store.checkpoint(syncId,{stage:"stock_publication",nextSkip:0,received:0,kind:"incoming",complete:true});await this.store.publish(syncId);return{state:await this.store.getState(),pages};}}await this.store.release(syncId,token);return{state:await this.store.getState(),pages};}catch(error){const current=await this.store.getState();await this.store.fail(syncId,current.currentStage??"physical_scan",current.pagesProcessed+1,error);return{state:await this.store.getState(),pages};}}
}

export class SupabaseStockSyncStore implements StockSyncStore{
 async start(){const current=await this.getState();if(["queued","running"].includes(current.status)&&Date.parse(current.updatedAt)>Date.now()-600_000)return{state:current,started:false};const client=createAdminClient();const{data:price}=await client.from("price_sync_state").select("status").eq("id","product_prices").maybeSingle();if(price?.status==="running"||price?.status==="queued")throw new Error("Price synchronization is active.");await this.clear(current.activeSyncId??current.lastFailedSyncId);const id=crypto.randomUUID(),now=new Date().toISOString();const{error}=await client.from("stock_sync_state").update({status:"queued",active_sync_id:id,last_failed_sync_id:null,snapshot_time:now,current_stage:"warehouse_scan",next_skip:0,page_size:PAGE_SIZE,pages_processed:0,physical_rows:0,reserved_rows:0,incoming_rows:0,warehouses_loaded:0,products_matched:0,products_unmatched:0,rows_published:0,rows_deactivated:0,scan_complete:false,started_at:now,error_category:null,failed_stage:null,safe_error:null,database_error_code:null,failed_page:null,active_chunk_token:null,chunk_started_at:null,updated_at:now}).eq("id","exact_stock");if(error)throw dbError(error);return{state:await this.getState(),started:true};}
 async getState(){const{data,error}=await createAdminClient().from("stock_sync_state").select("*").eq("id","exact_stock").single();if(error||!data)throw dbError(error);return mapState(data);}
 async claim(id:string,token:string){const{data,error}=await createAdminClient().rpc("claim_stock_sync_chunk",{p_sync_id:id,p_token:token});if(error)throw dbError(error);return data===true;}
 async release(id:string,token:string){const{error}=await createAdminClient().from("stock_sync_state").update({active_chunk_token:null,chunk_started_at:null,updated_at:new Date().toISOString()}).eq("id","exact_stock").eq("active_sync_id",id).eq("active_chunk_token",token);if(error)throw dbError(error);}
 async stageWarehouses(id:string,rows:StockWarehouseRow[]){if(!rows.length)return 0;const{error}=await createAdminClient().from("stock_warehouse_sync_stage").upsert(rows.map(r=>({sync_id:id,external_ref:r.externalRef,code:r.code,name:r.name,organization_ref:r.organizationRef,is_active:r.isActive})),{onConflict:"sync_id,external_ref"});if(error)throw dbError(error);return rows.length;}
 async stageBalances(id:string,kind:StockBalanceKind,rows:StockStageRow[]){if(!rows.length)return 0;const{data,error}=await createAdminClient().rpc("stage_stock_balance_rows",{p_sync_id:id,p_kind:kind,p_rows:rows.map(r=>({external_product_ref:r.externalProductRef,external_warehouse_ref:r.externalWarehouseRef,external_characteristic_ref:r.externalCharacteristicRef,quantity:r.quantity}))});if(error)throw dbError(error);return Number(data??0);}
 async checkpoint(id:string,input:{stage:StockSyncStage;nextSkip:number;received:number;kind:StockBalanceKind|"warehouses";complete?:boolean}){const s=await this.getState();const payload:Record<string,unknown>={status:"running",current_stage:input.stage,next_skip:input.nextSkip,pages_processed:s.pagesProcessed+1,scan_complete:input.complete??s.scanComplete,updated_at:new Date().toISOString()};payload[input.kind==="warehouses"?"warehouses_loaded":`${input.kind}_rows`]=(input.kind==="warehouses"?s.warehousesLoaded:input.kind==="physical"?s.physicalRows:input.kind==="reserved"?s.reservedRows:s.incomingRows)+input.received;const{error}=await createAdminClient().from("stock_sync_state").update(payload).eq("id","exact_stock").eq("active_sync_id",id);if(error)throw dbError(error);}
 async publish(id:string){const{error}=await createAdminClient().rpc("publish_exact_stock_snapshot",{p_sync_id:id});if(error)throw dbError(error);}
 async fail(id:string,stage:StockSyncStage,page:number,error:unknown){const e=error as{code?:string};await createAdminClient().from("stock_sync_state").update({status:"failed",last_failed_sync_id:id,active_sync_id:null,failed_stage:stage,failed_page:page,error_category:"stock_sync_failure",database_error_code:e?.code??null,safe_error:"Exact stock synchronization failed.",active_chunk_token:null,chunk_started_at:null,updated_at:new Date().toISOString()}).eq("id","exact_stock").eq("active_sync_id",id);}
 async failLaunch(id:string,message:string){await createAdminClient().from("stock_sync_state").update({status:"failed",last_failed_sync_id:id,active_sync_id:null,failed_stage:"continuation_launch",error_category:"orchestration_failure",safe_error:message,updated_at:new Date().toISOString()}).eq("id","exact_stock").eq("active_sync_id",id);}
 private async clear(id:string|null){if(!id)return;const c=createAdminClient();await Promise.all([c.from("stock_balance_sync_stage").delete().eq("sync_id",id),c.from("stock_warehouse_sync_stage").delete().eq("sync_id",id)]);}
}
function nextStage(s:StockSyncStage):StockSyncStage{return s==="warehouse_scan"?"physical_scan":s==="physical_scan"?"reserved_scan":s==="reserved_scan"?"incoming_scan":s==="incoming_scan"?"stock_publication":s;}
function kindFor(s:StockSyncStage):StockBalanceKind{return s==="physical_scan"?"physical":s==="reserved_scan"?"reserved":"incoming";}
function dbError(error:unknown){const code=typeof error==="object"&&error&&"code"in error?String(error.code):undefined;return Object.assign(new Error("Stock persistence failed."),{code});}
function mapState(r:Record<string,unknown>):StockSyncState{return{status:r.status as StockSyncStatus,activeSyncId:str(r.active_sync_id),lastFailedSyncId:str(r.last_failed_sync_id),snapshotTime:str(r.snapshot_time),currentStage:r.current_stage as StockSyncStage|null,nextSkip:num(r.next_skip),pageSize:num(r.page_size),pagesProcessed:num(r.pages_processed),physicalRows:num(r.physical_rows),reservedRows:num(r.reserved_rows),incomingRows:num(r.incoming_rows),warehousesLoaded:num(r.warehouses_loaded),productsMatched:num(r.products_matched),productsUnmatched:num(r.products_unmatched),rowsPublished:num(r.rows_published),rowsDeactivated:num(r.rows_deactivated),scanComplete:r.scan_complete===true,startedAt:str(r.started_at),lastSuccessfulSyncAt:str(r.last_successful_sync_at),errorCategory:str(r.error_category),failedStage:str(r.failed_stage),safeError:str(r.safe_error),failedPage:typeof r.failed_page==="number"?r.failed_page:null,updatedAt:String(r.updated_at)};}
function str(v:unknown){return typeof v==="string"?v:null;}function num(v:unknown){return typeof v==="number"?v:0;}
