import Image from "next/image";
import Link from "next/link";
import { PublicRetailAddToCartButton } from "@/src/modules/public-retail/components/PublicRetailAddToCartButton";
import { createFinalCustomerService, getFinalCustomerContext } from "@/src/modules/final-customer/server";
import { getFinalCustomerLocale } from "@/src/modules/final-customer/locale";
import { buyAgainAllowed, customerDate, customerMoney } from "@/src/modules/final-customer/presentation";
import { CustomerEmptyState, CustomerPager } from "@/src/modules/final-customer/components";

export default async function PurchasesPage({ searchParams }: { searchParams: Promise<{ page?: string }> }) {
  const [context, locale] = await Promise.all([getFinalCustomerContext(), getFinalCustomerLocale()]);
  const page = positivePage((await searchParams).page); const pageSize = 20;
  const result = await createFinalCustomerService().purchases(context.account, pageSize + 1, (page - 1) * pageSize);
  const purchases = result.slice(0, pageSize); const hasNext = result.length > pageSize;
  const ro = locale === "ro";
  return <main className="mx-auto max-w-5xl space-y-5 px-4 py-6 sm:py-8"><header><h1 className="text-2xl font-semibold">{ro ? "Cumpărături" : "Покупки"}</h1><p className="mt-1 text-sm text-zinc-600">{ro ? "Produse numai din comenzi plătite și confirmate." : "Товары только из оплаченных и подтверждённых заказов."}</p></header>{purchases.length ? <ul className="grid gap-3">{purchases.map((line) => <li className="grid gap-3 rounded-xl border border-zinc-200 bg-white p-4 sm:grid-cols-[56px_minmax(0,1fr)_auto] sm:items-center" key={line.id}><div className="relative size-14 overflow-hidden rounded-lg bg-zinc-100">{(line.currentProduct?.imageUrl ?? line.imageUrl) ? <Image alt="" fill className="object-contain p-1" sizes="56px" src={line.currentProduct?.imageUrl ?? line.imageUrl ?? ""} /> : null}</div><div className="min-w-0"><Link className="font-semibold hover:text-emerald-700" href={`/account/equipment/${line.id}`}>{line.name}</Link><p className="mt-1 text-xs text-zinc-500">SKU {line.sku} · {customerDate(line.purchasedAt, locale)} · <Link className="font-medium text-emerald-700" href={`/account/orders/${line.orderId}`}>{line.orderNumber}</Link></p><p className="mt-1 text-sm">{line.quantity} × {customerMoney(line.unitPrice, line.currency, locale)}</p>{line.currentProduct ? <Link className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-emerald-700" href={`/products/${line.currentProduct.slug}?lang=${locale}`}>{ro ? "Produsul actual" : "Текущий товар"}</Link> : null}</div><div className="w-full sm:w-40">{line.currentProduct && buyAgainAllowed(line.currentProduct.availability) ? <PublicRetailAddToCartButton compact locale={locale} publicProductId={line.currentProduct.publicProductId} source="product_detail" /> : <p className="text-xs text-zinc-500">{ro ? "Indisponibil momentan" : "Сейчас недоступен"}</p>}</div></li>)}</ul> : <CustomerEmptyState body={ro ? "Aici apar numai produsele din comenzi achitate și confirmate. Coșul și comenzile neplătite nu sunt considerate cumpărături." : "Здесь появятся только товары из оплаченных и подтверждённых заказов. Корзина и неоплаченные заказы не считаются покупками."} locale={locale} title={ro ? "Nu există cumpărături confirmate" : "Подтверждённых покупок пока нет"} />}<CustomerPager hasNext={hasNext} page={page} path="/account/purchases" ro={ro} /></main>;
}
function positivePage(value?: string) { const page = Number(value); return Number.isInteger(page) && page > 0 ? Math.min(page, 1000) : 1; }
