import type { PartnerLocale } from "../partner-locale";

const COPY = {
  ru: {
    tab: "Аналитика",
    title: "Конкурентные цены",
    benefit: "Сохраняйте цены других поставщиков. Здесь формируется история изменений и сравнение с вашей ценой Novotech.",
    addFirst: "Добавить первую цену",
    competitor: "Конкурент",
    otherCompetitor: "Другой конкурент",
    competitorName: "Название конкурента",
    price: "Цена",
    currency: "Валюта",
    vat: "НДС",
    quantity: "Количество",
    date: "Дата",
    save: "Сохранить цену",
    saving: "Сохранение...",
    details: "Дополнительные условия",
    validity: "Действительно до",
    payment: "Условия оплаты",
    delivery: "Условия поставки",
    source: "Источник",
    comment: "Комментарий",
    evidence: "Подтверждение",
    history: "Ваша история",
    trend: "Динамика цен",
    noHistory: "Для этого товара пока нет сохранённых наблюдений.",
    currentSummary: "Последнее сравнение",
    competitorPrice: "Цена конкурента",
    novotechPrice: "Цена Novotech при наблюдении",
    difference: "Разница",
    sourceLabels: { verbal: "Устно", message: "Сообщение", quotation: "Предложение", order: "Заказ", invoice: "Счёт", other: "Другое" },
    vatLabels: { included: "Включён", excluded: "Без НДС", not_applicable: "Не применяется", not_specified: "Не указан" },
  },
  ro: {
    tab: "Analiză",
    title: "Prețuri competitive",
    benefit: "Salvați prețurile altor furnizori. Aici se formează istoricul și comparația cu prețul dvs. Novotech.",
    addFirst: "Adaugă primul preț",
    competitor: "Concurent",
    otherCompetitor: "Alt concurent",
    competitorName: "Denumirea concurentului",
    price: "Preț",
    currency: "Valută",
    vat: "TVA",
    quantity: "Cantitate",
    date: "Data",
    save: "Salvează prețul",
    saving: "Se salvează...",
    details: "Condiții suplimentare",
    validity: "Valabil până la",
    payment: "Condiții de plată",
    delivery: "Condiții de livrare",
    source: "Sursă",
    comment: "Comentariu",
    evidence: "Dovadă",
    history: "Istoricul dvs.",
    trend: "Evoluția prețurilor",
    noHistory: "Nu există încă observații salvate pentru acest produs.",
    currentSummary: "Ultima comparație",
    competitorPrice: "Preț concurent",
    novotechPrice: "Preț Novotech la observare",
    difference: "Diferență",
    sourceLabels: { verbal: "Verbal", message: "Mesaj", quotation: "Ofertă", order: "Comandă", invoice: "Factură", other: "Altele" },
    vatLabels: { included: "Inclus", excluded: "Fără TVA", not_applicable: "Nu se aplică", not_specified: "Nespecificat" },
  },
} as const;

export function getCompetitiveIntelligenceCopy(locale: PartnerLocale) {
  return COPY[locale];
}
