import type { PartnerLocale } from "../partner-locale";

const COPY = {
  ru: {
    tab: "Аналитика",
    title: "Конкурентные цены",
    benefit: "Сохраняйте цены конкурентов по каждой модели, чтобы видеть историю и динамику рынка, сравнивать предложения с вашими условиями Novotech и быстрее принимать решения о закупке. Регулярные наблюдения делают рыночную картину и рекомендации точнее, а переговорную позицию — сильнее.",
    addFirst: "Добавить первую цену",
    competitor: "Конкурент",
    otherCompetitor: "Другой конкурент",
    competitorName: "Название конкурента",
    price: "Цена",
    currency: "Валюта",
    quantity: "Количество",
    date: "Дата",
    save: "Сохранить цену",
    saving: "Сохранение...",
    details: "Дополнительные условия",
    payment: "Условия оплаты",
    delivery: "Условия поставки",
    source: "Источник",
    comment: "Комментарий",
    evidence: "Подтверждение",
    history: "Ваша история",
    trend: "Динамика цен",
    noHistory: "Для этого товара пока нет сохранённых наблюдений.",
    currentSummary: "Последнее сравнение",
    competitorPrice: "Цена конкурента",
    novotechPrice: "Цена Novotech при наблюдении",
    difference: "Разница",
    sourceLabels: { verbal: "Устно", message: "Сообщение", quotation: "Предложение", order: "Заказ", invoice: "Счёт", other: "Другое" },
  },
  ro: {
    tab: "Analiză",
    title: "Prețuri competitive",
    benefit: "Salvați prețurile concurenților pentru fiecare model ca să urmăriți istoricul și evoluția pieței, să comparați ofertele cu condițiile dvs. Novotech și să luați mai rapid decizii de achiziție. Observațiile regulate fac imaginea pieței și recomandările mai precise, iar poziția de negociere mai puternică.",
    addFirst: "Adaugă primul preț",
    competitor: "Concurent",
    otherCompetitor: "Alt concurent",
    competitorName: "Denumirea concurentului",
    price: "Preț",
    currency: "Valută",
    quantity: "Cantitate",
    date: "Data",
    save: "Salvează prețul",
    saving: "Se salvează...",
    details: "Condiții suplimentare",
    payment: "Condiții de plată",
    delivery: "Condiții de livrare",
    source: "Sursă",
    comment: "Comentariu",
    evidence: "Dovadă",
    history: "Istoricul dvs.",
    trend: "Evoluția prețurilor",
    noHistory: "Nu există încă observații salvate pentru acest produs.",
    currentSummary: "Ultima comparație",
    competitorPrice: "Preț concurent",
    novotechPrice: "Preț Novotech la observare",
    difference: "Diferență",
    sourceLabels: { verbal: "Verbal", message: "Mesaj", quotation: "Ofertă", order: "Comandă", invoice: "Factură", other: "Altele" },
  },
} as const;

export function getCompetitiveIntelligenceCopy(locale: PartnerLocale) {
  return COPY[locale];
}
