import { Archive, Copy, Plus, ShoppingCart } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";

import { BehaviorViewEvent } from "@/src/modules/behavior-analytics/components";
import { listPurchaseTemplatesAction } from "@/src/modules/purchase-templates/actions";

type SearchParams = Promise<{ search?: string | string[]; filter?: string | string[]; page?: string | string[] }>;

export default async function PurchaseTemplatesPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const search = single(params.search);
  const filter = normalizeFilter(single(params.filter));
  const page = Math.max(1, Number(single(params.page)) || 1);
  const result = await listPurchaseTemplatesAction({ search, filter, page });
  if (!result.success && result.errorCode === "AUTH_REQUIRED") redirect("/auth/sign-in");
  if (!result.success) return <p className="border border-rose-200 bg-rose-50 p-5 text-sm text-rose-800">Не удалось загрузить шаблоны. Обновите страницу позже.</p>;
  return <div className="space-y-6">
    <BehaviorViewEvent dedupeKey={`purchase-templates:${filter}:${page}:${search}`} eventName="purchase_templates_opened" resultCount={result.data.totalCount} route="/cabinet/purchase-templates" searchQuery={search || undefined} sourceSurface="purchase_template_list" />
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-zinc-200 pb-5"><div><p className="text-xs font-semibold uppercase text-emerald-700">Повторные закупки</p><h1 className="mt-1 text-2xl font-semibold text-zinc-950">Шаблоны закупок</h1><p className="mt-2 max-w-2xl text-sm text-zinc-600">Сохраняйте состав и количество. Цены, наличие и поступления проверяются заново перед добавлением в корзину.</p></div><Link className="inline-flex min-h-11 items-center gap-2 rounded-md bg-emerald-700 px-4 text-sm font-semibold text-white" href="/cabinet/purchase-templates/new" prefetch={false}><Plus className="size-4" />Новый шаблон</Link></header>
    <form className="flex flex-wrap gap-2" method="get"><input className="h-11 min-w-0 flex-1 rounded-md border border-zinc-300 px-3 sm:max-w-md" defaultValue={search} name="search" placeholder="Название, описание, SKU или товар" /><select className="h-11 rounded-md border border-zinc-300 px-3" defaultValue={filter} name="filter"><option value="all">Все активные</option><option value="mine">Мои</option><option value="company">Для компании</option><option value="active">Активные</option><option value="archived">Архив</option></select><button className="h-11 rounded-md border border-zinc-300 px-4 text-sm font-semibold" type="submit">Показать</button></form>
    {!result.data.records.length ? <section className="border border-dashed border-zinc-300 bg-white px-6 py-12 text-center"><h2 className="font-semibold">Шаблоны не найдены</h2><p className="mt-1 text-sm text-zinc-600">Создайте пустой шаблон или сохраните текущую корзину, заказ или список закупок.</p></section> : <ul className="grid gap-3 lg:grid-cols-2">{result.data.records.map((template) => <li className="border border-zinc-200 bg-white p-4" key={template.id}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-semibold uppercase text-zinc-500">{template.visibility === "private" ? "Личный" : "Для компании"}{template.status === "archived" ? " · Архив" : ""}</p><Link className="mt-1 block truncate text-lg font-semibold text-zinc-950 hover:text-emerald-700" href={`/cabinet/purchase-templates/${template.id}`} prefetch={false}>{template.name}</Link><p className="mt-1 text-xs text-zinc-500">Владелец: {template.ownerName}</p></div>{template.warningCount ? <span className="shrink-0 rounded bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-800">Предупреждений: {template.warningCount}</span> : null}</div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><Metric label="Позиций" value={String(template.itemCount)} /><Metric label="Использований" value={String(template.usageCount)} /><Metric label="Обновлён" value={formatDate(template.updatedAt)} /><Metric label="Последний запуск" value={template.lastUsedAt ? formatDate(template.lastUsedAt) : "Ещё не запускался"} /></dl>{template.totals.length ? <p className="mt-3 text-sm font-semibold">Текущая сумма: {template.totals.map((total) => total.formatted).join(" · ")}</p> : <p className="mt-3 text-sm text-zinc-500">Текущая сумма недоступна</p>}<div className="mt-4 flex flex-wrap gap-2"><Link className="inline-flex min-h-11 items-center rounded-md border border-zinc-300 px-3 text-sm font-semibold" href={`/cabinet/purchase-templates/${template.id}`} prefetch={false}>Открыть</Link>{template.status === "active" ? <Link className="inline-flex min-h-11 items-center gap-2 rounded-md bg-emerald-700 px-3 text-sm font-semibold text-white" href={`/cabinet/purchase-templates/${template.id}`} prefetch={false}><ShoppingCart className="size-4" />Проверить и добавить в корзину</Link> : null}{template.canEdit ? <span className="sr-only"><Copy />Создать копию<Archive />Архивировать</span> : null}</div></li>)}</ul>}
    <nav className="flex items-center justify-between border-t border-zinc-200 pt-4">{result.data.page > 1 ? <Link className="min-h-11 rounded-md border border-zinc-300 px-4 py-2 text-sm" href={href(search, filter, result.data.page - 1)} prefetch={false}>Назад</Link> : <span />}<span className="text-sm text-zinc-500">Страница {result.data.page} из {result.data.totalPages}</span>{result.data.page < result.data.totalPages ? <Link className="min-h-11 rounded-md border border-zinc-300 px-4 py-2 text-sm" href={href(search, filter, result.data.page + 1)} prefetch={false}>Далее</Link> : <span />}</nav>
  </div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-zinc-500">{label}</dt><dd className="mt-1 font-medium text-zinc-900">{value}</dd></div>; }
function single(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }
function normalizeFilter(value: string): "all" | "mine" | "company" | "active" | "archived" { return ["mine", "company", "active", "archived"].includes(value) ? value as never : "all"; }
function href(search: string, filter: string, page: number) { const params = new URLSearchParams(); if (search) params.set("search", search); if (filter !== "all") params.set("filter", filter); if (page > 1) params.set("page", String(page)); return `/cabinet/purchase-templates?${params}`; }
function formatDate(value: string) { return new Date(value).toLocaleDateString("ru-RU"); }
