import "server-only";
import { MembershipStatus } from "../access-control/types";
import { DomainConflictError, type CompanyAccessService } from "../access-control/services";
import { PartnerSupportRepositoryError, type PartnerSupportRepository } from "./repository";
import { SUPPORT_CATEGORIES, SUPPORT_PRIORITIES, SUPPORT_STATUSES, type SupportPriority, type SupportStatus } from "./types";

export class PartnerSupportValidationError extends Error { constructor(message: string) { super(message); this.name = "PartnerSupportValidationError"; } }
export class PartnerSupportService {
  constructor(private readonly repository: PartnerSupportRepository, private readonly companyAccess: CompanyAccessService) {}
  async listPartner(userId: string, input: { query?: unknown; filter?: unknown; page?: unknown }) { return this.repository.listPartner({ companyId: await this.companyId(userId), query: bounded(input.query, 100), filter: ["active", "waiting", "closed", "all"].includes(String(input.filter)) ? String(input.filter) : "active", page: positiveInt(input.page) }); }
  async getPartner(userId: string, ticketId: string) { await this.companyId(userId); return this.repository.get(uuid(ticketId)); }
  async create(userId: string, input: { description: string; priority: string; idempotencyKey: string; locale: string }) { const description = bounded(input.description, 5000); if (description.length < 20) throw new PartnerSupportValidationError("Опишите проблему минимум в 20 символах."); if (!SUPPORT_PRIORITIES.includes(input.priority as SupportPriority)) throw new PartnerSupportValidationError("Выберите приоритет."); return this.repository.create({ companyId: await this.companyId(userId), description, priority: input.priority as SupportPriority, idempotencyKey: uuid(input.idempotencyKey), locale: input.locale === "ro" ? "ro" : "ru" }); }
  async reply(userId: string, input: { ticketId: string; expectedVersion: number; message: string }) { await this.companyId(userId); const message = bounded(input.message, 5000); if (message.length < 2) throw new PartnerSupportValidationError("Введите сообщение."); return supportMutation(() => this.repository.reply({ ticketId: uuid(input.ticketId), expectedVersion: positiveInt(input.expectedVersion), message })); }
  async partnerTransition(userId: string, input: { ticketId: string; expectedVersion: number; action: string }) { await this.companyId(userId); if (!(["confirm_solution", "reopen", "cancel"] as const).includes(input.action as never)) throw new PartnerSupportValidationError("Недоступное действие."); return supportMutation(() => this.repository.partnerTransition({ ticketId: uuid(input.ticketId), expectedVersion: positiveInt(input.expectedVersion), action: input.action as "confirm_solution" | "reopen" | "cancel" })); }
  listAdmin(input: Record<string, unknown>) { const modes = ["new", "high_priority", "unassigned", "waiting", "overdue", "resolved"]; return this.repository.listAdmin({ query: bounded(input.query, 100), status: SUPPORT_STATUSES.includes(input.status as SupportStatus) ? input.status as string : null, priority: SUPPORT_PRIORITIES.includes(input.priority as SupportPriority) ? input.priority as string : null, mode: modes.includes(input.mode as string) ? input.mode as string : null, company: bounded(input.company, 100), assigneeId: optionalUuid(input.assignee), category: SUPPORT_CATEGORIES.includes(input.category as never) ? input.category as string : null, createdFrom: isoDate(input.createdFrom), createdTo: isoDate(input.createdTo), page: positiveInt(input.page) }); }
  listAssignees() { return this.repository.listAssignees(); }
  getAdmin(ticketId: string) { return this.repository.get(uuid(ticketId)); }
  transition(input: { ticketId: string; expectedVersion: number; status: string; partnerReply: string; internalNote: string; assigneeId: string | null; category: string | null; effectivePriority: string | null; priorityReason: string }) { if (!SUPPORT_STATUSES.includes(input.status as SupportStatus)) throw new PartnerSupportValidationError("Выберите статус."); return supportMutation(() => this.repository.transition({ ticketId: uuid(input.ticketId), expectedVersion: positiveInt(input.expectedVersion), status: input.status as SupportStatus, partnerReply: bounded(input.partnerReply, 5000), internalNote: bounded(input.internalNote, 5000), assigneeId: input.assigneeId ? uuid(input.assigneeId) : null, category: SUPPORT_CATEGORIES.includes(input.category as never) ? input.category : null, effectivePriority: SUPPORT_PRIORITIES.includes(input.effectivePriority as SupportPriority) ? input.effectivePriority as SupportPriority : null, priorityReason: bounded(input.priorityReason, 1000) })); }
  async dashboard(userId: string) { return this.repository.dashboard(await this.companyId(userId)); }
  diagnostics() { return this.repository.diagnostics(); }
  private async companyId(userId: string) { const membership = (await this.companyAccess.getOwnMemberships(userId)).find((item) => item.status === MembershipStatus.Active); if (!membership) throw new PartnerSupportValidationError("Активная компания не найдена."); return (await this.companyAccess.getActiveCompanyContext(userId, membership.companyId)).company.id; }
}
async function supportMutation<T>(operation: () => Promise<T>) { try { return await operation(); } catch (error) { if (error instanceof PartnerSupportRepositoryError && error.code === "PT409") throw new DomainConflictError("SUPPORT_TICKET_CONFLICT", "Заявка изменилась. Обновите страницу и повторите действие."); throw error; } }
function bounded(value: unknown, max: number) { return typeof value === "string" ? value.trim().slice(0, max) : ""; }
function positiveInt(value: unknown) { const number = Number(value); return Number.isSafeInteger(number) && number > 0 ? Math.min(number, 100000) : 1; }
function uuid(value: string) { const result = value.trim(); if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(result)) throw new PartnerSupportValidationError("Некорректный идентификатор."); return result; }
function optionalUuid(value: unknown) { const result = bounded(value, 36); return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(result) ? result : null; }
function isoDate(value: unknown) { const result = bounded(value, 10); return /^\d{4}-\d{2}-\d{2}$/.test(result) ? result : null; }
