import Link from "next/link";

import { AdminPageHeader } from "@/src/modules/admin/components";
import { requireAdminPagePermission } from "@/src/modules/admin/services";
import { createCommercialCampaignService } from "@/src/modules/commercial-campaigns/actions";
import { CampaignAdminActions } from "@/src/modules/commercial-campaigns/components";
import { readableCampaignText, SPECIAL_OFFERS_COPY } from "@/src/modules/commercial-campaigns/copy";
import type { CampaignStatus, CampaignType } from "@/src/modules/commercial-campaigns/types";

const STATUSES: ReadonlyArray<["all" | CampaignStatus, string]> = [["all", "Все"], ["draft", "Черновики"], ["scheduled", "Запланированные"], ["active", "Активные"], ["paused", "Приостановленные"], ["completed", "Завершённые"], ["archived", "Архив"]];
const TYPES: ReadonlyArray<["all" | CampaignType, string]> = [["all", "Все типы"], ["product_offer", "Товарное предложение"], ["stock_clearance", "Остатки"], ["arrival_promotion", "Поступление"], ["reorder_campaign", "Повторная закупка"], ["category_campaign", "Категория"], ["partner_segment_offer", "Сегмент партнёров"]];
type Query = { page?: string; status?: string; search?: string; type?: string; from?: string; to?: string };

export default async function AdminCampaignsPage({ searchParams }: { searchParams: Promise<Query> }) {
  const context = await requireAdminPagePermission("campaigns.view");
  const query = await searchParams;
  const page = Math.max(1, Number(query.page) || 1);
  const status = STATUSES.some(([value]) => value === query.status) ? query.status as "all" | CampaignStatus : "all";
  const campaignType = TYPES.some(([value]) => value === query.type) ? query.type as "all" | CampaignType : "all";
  const result = await createCommercialCampaignService().listAdmin({ page, pageSize: 20, status, campaignType, search: query.search, dateFrom: query.from, dateTo: query.to });
  const totalPages = Math.max(1, Math.ceil(result.totalCount / 20));
  const permissions = new Set(context.permissions);
  return <div className="min-w-0 space-y-5"><AdminPageHeader description="Операционное управление черновиками, публикацией, аудиториями и жизненным циклом предложений." eyebrow="Коммерческие инструменты" title={SPECIAL_OFFERS_COPY.ru.title} />
    <div className="flex flex-wrap items-center justify-between gap-3">{permissions.has("campaigns.create") ? <Link className="inline-flex min-h-11 items-center rounded-md bg-emerald-700 px-4 text-sm font-semibold text-white" href="/admin/commercial/campaigns/new">{SPECIAL_OFFERS_COPY.ru.create}</Link> : <span /> }<span className="text-sm text-zinc-600">Всего: {result.totalCount}</span></div>
    <nav aria-label="Статусы предложений" className="flex gap-2 overflow-x-auto pb-1">{STATUSES.map(([value, label]) => <Link className={`whitespace-nowrap rounded-full border px-3 py-2 text-sm ${status === value ? "border-emerald-600 bg-emerald-50 text-emerald-800" : "border-zinc-200"}`} href={href({ ...query, status: value, page: "1" })} key={value}>{label}</Link>)}</nav>
    <form className="grid gap-3 rounded-md border border-zinc-200 bg-white p-4 md:grid-cols-2 xl:grid-cols-[minmax(14rem,1fr)_14rem_11rem_11rem_auto]" method="get"><label className="grid gap-1 text-xs font-medium">Поиск<input className="min-h-10 rounded-md border px-3 text-sm" defaultValue={query.search} name="search" placeholder="Код, внутреннее название, заголовок" /></label><label className="grid gap-1 text-xs font-medium">Тип<select className="min-h-10 rounded-md border px-3 text-sm" defaultValue={campaignType} name="type">{TYPES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-1 text-xs font-medium">Период с<input className="min-h-10 rounded-md border px-3 text-sm" defaultValue={query.from} name="from" type="date" /></label><label className="grid gap-1 text-xs font-medium">Период по<input className="min-h-10 rounded-md border px-3 text-sm" defaultValue={query.to} name="to" type="date" /></label><input name="status" type="hidden" value={status} /><button className="min-h-10 self-end rounded-md bg-zinc-900 px-4 text-sm font-semibold text-white md:col-span-2 xl:col-span-1" type="submit">Применить</button></form>
    <div className="max-w-full overflow-x-auto border border-zinc-200 bg-white"><table className="w-full min-w-[1080px] text-left text-sm"><thead className="bg-zinc-50 text-zinc-600"><tr><th className="p-3">Предложение</th><th className="p-3">Статус</th><th className="p-3">Период</th><th className="p-3">Товары</th><th className="p-3">Аудитория</th><th className="p-3">Приоритет</th><th className="p-3">Изменено</th><th className="p-3">Действия</th></tr></thead><tbody>{result.items.map((campaign) => <tr className="border-t border-zinc-200 align-top" key={campaign.id}><td className="p-3"><Link className="font-semibold text-emerald-700" href={`/admin/commercial/campaigns/${campaign.id}`}>{readableCampaignText(campaign.partnerTitle, readableCampaignText(campaign.name, campaign.code))}</Link><p className="text-xs text-zinc-500">{campaign.code} · {readableCampaignText(campaign.name, "Без названия")}</p></td><td className="p-3">{statusLabel(campaign.status)}</td><td className="p-3">{date(campaign.startsAt)} — {date(campaign.endsAt)}</td><td className="p-3">{campaign.itemCount}</td><td className="p-3">{campaign.audienceCount || "Правило"}</td><td className="p-3">{campaign.priority}</td><td className="p-3">{dateTime(campaign.updatedAt)}</td><td className="p-3"><CampaignAdminActions campaignId={campaign.id} canCreate={permissions.has("campaigns.create")} canEdit={permissions.has("campaigns.edit")} canPause={permissions.has("campaigns.pause")} canPublish={permissions.has("campaigns.publish")} compact status={campaign.status} /></td></tr>)}</tbody></table></div>
    {!result.items.length ? <p className="border border-dashed border-zinc-300 p-8 text-center">Предложения по выбранным условиям не найдены.</p> : null}
    <nav aria-label="Страницы" className="flex items-center justify-between"><Link aria-disabled={page <= 1} className={`rounded-md border px-4 py-2 text-sm ${page <= 1 ? "pointer-events-none opacity-40" : ""}`} href={href({ ...query, page: String(page - 1) })}>Назад</Link><span className="text-sm">{page} / {totalPages}</span><Link aria-disabled={page >= totalPages} className={`rounded-md border px-4 py-2 text-sm ${page >= totalPages ? "pointer-events-none opacity-40" : ""}`} href={href({ ...query, page: String(page + 1) })}>Далее</Link></nav>
  </div>;
}
function href(query: Query) { const params = new URLSearchParams(); for (const [key, value] of Object.entries(query)) if (value) params.set(key, value); return `/admin/commercial/campaigns?${params}`; }
function date(value: string) { return new Intl.DateTimeFormat("ru-RU").format(new Date(value)); }
function dateTime(value: string) { return new Intl.DateTimeFormat("ru-RU", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }
function statusLabel(value: string) { return ({ draft: "Черновик", scheduled: "Запланировано", active: "Активно", paused: "Приостановлено", completed: "Завершено", archived: "Архив" } as Record<string, string>)[value] ?? value; }
