import Link from "next/link";
import { notFound } from "next/navigation";
import { Download } from "lucide-react";
import { requireAdminPagePermission } from "@/src/modules/admin/services";
import { updateCustomerServiceRequestStatusAction } from "@/src/modules/final-customer/admin-actions";
import { createFinalCustomerService } from "@/src/modules/final-customer/server";
import { customerDate, serviceStatusLabel, serviceTypeLabel } from "@/src/modules/final-customer/presentation";
import { allowedAdminServiceTransitions } from "@/src/modules/final-customer/service-lifecycle";

export default async function AdminCustomerServiceDetailPage({ params }: { params: Promise<{ requestId: string }> }) {
  await requireAdminPagePermission("admin.service.view");
  const { requestId } = await params;
  const request = await createFinalCustomerService().findAdminServiceRequest(requestId); if (!request) notFound();
  const transitions = allowedAdminServiceTransitions(request.status);
  return <div className="max-w-4xl space-y-5">
    <header><Link className="text-sm font-semibold text-emerald-700" href="/admin/service/customers">← Обращения клиентов</Link><p className="mt-3 font-mono text-xs text-zinc-500">{request.number}</p><div className="mt-1 flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-semibold">{request.subject}</h1><span className="rounded-full bg-zinc-100 px-3 py-1 text-sm font-semibold">{serviceStatusLabel(request.status, "ru")}</span></div><p className="mt-2 text-sm text-zinc-600">{serviceTypeLabel(request.type, "ru")} · {customerDate(request.createdAt, "ru")}</p></header>
    <section className="rounded-lg border border-zinc-200 bg-white p-5"><h2 className="text-sm font-semibold">Обращение клиента</h2><dl className="mt-2 grid gap-1 text-sm sm:grid-cols-2"><div><dt className="text-xs text-zinc-500">Клиент</dt><dd>{request.customerDisplayName ?? "Имя не указано"}</dd></div>{request.customerEmail ? <div><dt className="text-xs text-zinc-500">Email</dt><dd>{request.customerEmail}</dd></div> : null}{request.relatedOrderNumber ? <div><dt className="text-xs text-zinc-500">Заказ</dt><dd>{request.relatedOrderNumber}</dd></div> : null}{request.relatedProductName ? <div><dt className="text-xs text-zinc-500">Товар</dt><dd>{request.relatedProductName}</dd></div> : null}</dl><p className="mt-4 whitespace-pre-wrap text-sm leading-6">{request.description}</p><p className="mt-4 text-xs text-zinc-500">Предпочтительная связь: {request.preferredContact === "EMAIL" ? "Email" : "Телефон"}</p></section>
    <section className="grid gap-3 sm:grid-cols-2"><div className="rounded-lg border border-zinc-200 bg-white p-4"><h2 className="font-semibold">Переписка с клиентом</h2><ol className="mt-3 space-y-3">{request.messages.filter((message) => message.visibility === "CUSTOMER_VISIBLE").map((message) => <li className="rounded-lg bg-zinc-50 p-3 text-sm" key={message.id}><p className="text-xs font-semibold text-zinc-500">{message.authorType === "CUSTOMER" ? "Клиент" : "Novotech"} · {customerDate(message.createdAt, "ru")}</p><p className="mt-1 whitespace-pre-wrap">{message.body}</p></li>)}</ol></div><div className="rounded-lg border border-amber-200 bg-amber-50 p-4"><h2 className="font-semibold text-amber-950">Внутренние заметки</h2><p className="mt-1 text-xs text-amber-800">Никогда не показываются клиенту.</p><ol className="mt-3 space-y-3">{request.messages.filter((message) => message.visibility === "INTERNAL").map((message) => <li className="rounded-lg bg-white/70 p-3 text-sm" key={message.id}>{message.body}</li>)}</ol></div></section>
    {request.attachments.length ? <section className="rounded-lg border border-zinc-200 bg-white p-4"><h2 className="font-semibold">Вложения</h2><ul className="mt-3 grid gap-2 sm:grid-cols-2">{request.attachments.map((attachment) => <li key={attachment.id}><a className="flex min-h-11 items-center gap-2 rounded-lg border border-zinc-200 px-3 text-sm" href={`/api/customer-service/attachments/${attachment.id}`}><Download aria-hidden className="size-4" /><span className="truncate">{attachment.fileName}</span>{attachment.visibility === "INTERNAL" ? <span className="ml-auto text-xs text-amber-700">внутр.</span> : null}</a></li>)}</ul></section> : null}
    {request.status === "CLOSED" || request.status === "CANCELLED" ? <p className="rounded-lg border border-zinc-200 bg-zinc-50 p-4 text-sm text-zinc-600">Жизненный цикл обращения завершён. История сохранена без изменений.</p> : <form action={updateCustomerServiceRequestStatusAction} className="space-y-4 rounded-lg border border-zinc-200 bg-white p-5"><input name="requestId" type="hidden" value={request.id} /><input name="expectedVersion" type="hidden" value={request.version} /><h2 className="font-semibold">Обновить обращение</h2><label className="block text-sm font-medium">Следующий статус<select className="mt-1 min-h-11 w-full rounded-md border border-zinc-300 px-3" defaultValue="" name="status"><option value="">Без изменения статуса</option>{transitions.map((status) => <option key={status} value={status}>{serviceStatusLabel(status, "ru")}</option>)}</select></label><label className="block text-sm font-medium">Ответ клиенту<textarea className="mt-1 min-h-28 w-full rounded-md border border-zinc-300 p-3" maxLength={4000} name="customerReply" placeholder="Обязателен при запросе информации" /></label><label className="block text-sm font-medium">Файлы для клиента<input accept="image/jpeg,image/png,image/webp,application/pdf" className="mt-1 min-h-11 w-full rounded-md border border-zinc-300 p-2" multiple name="customerFiles" type="file" /></label><div className="rounded-lg border border-amber-200 bg-amber-50 p-3"><label className="block text-sm font-medium text-amber-950">Внутренняя заметка<textarea className="mt-1 min-h-24 w-full rounded-md border border-amber-300 bg-white p-3" maxLength={4000} name="internalNote" /></label><label className="mt-3 block text-sm font-medium text-amber-950">Внутренние файлы<input accept="image/jpeg,image/png,image/webp,application/pdf" className="mt-1 min-h-11 w-full rounded-md border border-amber-300 bg-white p-2" multiple name="internalFiles" type="file" /></label></div><button className="min-h-11 rounded-md bg-zinc-900 px-4 text-sm font-semibold text-white">Сохранить обновление</button></form>}
    <section><h2 className="font-semibold">Аудит</h2><ol className="mt-2 border-l border-zinc-200 pl-4">{request.timeline.map((event) => <li className="pb-3 text-sm" key={event.id}>{event.eventType}{event.toStatus ? ` → ${serviceStatusLabel(event.toStatus, "ru")}` : ""}<span className="ml-2 text-xs text-zinc-500">{customerDate(event.createdAt, "ru")}</span></li>)}</ol></section>
  </div>;
}
