import {
  prepareInstallationMarketplaceInvitationAction,
  reviewInstallationMarketplaceActivationAction,
  saveInstallationMarketplacePilotConfigurationAction,
  sendInstallationMarketplaceInvitationAction,
} from "./actions";
import type { InstallationMarketplaceSupplyReport } from "./types";

const readinessTone = {
  READY: "bg-emerald-50 text-emerald-800",
  LIMITED: "bg-amber-50 text-amber-800",
  NOT_READY: "bg-red-50 text-red-800",
} as const;

export function InstallationMarketplaceSupplyPilot({ report, query }: { report: InstallationMarketplaceSupplyReport; query: Record<string, string | string[] | undefined> }) {
  return <main className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">Installation supply pilot</p><h1 className="mt-1 text-2xl font-semibold">Исполнители монтажа</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-600">Фактическая готовность B2B-партнёров, покрытие пилота и управляемые приглашения. Отправка выполняется только вручную.</p></div><a className="inline-flex min-h-11 items-center rounded-md border border-zinc-300 px-4 text-sm font-semibold" href="/admin/retail/installation?section=operations">Операции</a></header>
    {query.pilot || query.invitation || query.activation ? <p className="border-l-4 border-emerald-600 bg-emerald-50 p-3 text-sm" role="status">Изменение сохранено.</p> : null}
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6" aria-label="Supply metrics">
      <Metric label="Партнёры" value={report.metrics.totalPartners}/><Metric label="Публичные профили" value={report.metrics.publicProfiles}/><Metric label="Потенциальные" value={report.metrics.potentialCandidates}/><Metric label="Приглашены" value={report.metrics.invited}/><Metric label="Начали" value={report.metrics.started}/><Metric label="Активны" value={report.metrics.active}/>
    </section>
    <section className="border border-zinc-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Готовность пилота</h2><p className="mt-1 text-sm text-zinc-600">Статус рассчитывается только по включённым регионам, компетенциям и фактическим активным исполнителям.</p></div><span className={`rounded px-3 py-2 text-xs font-semibold ${readinessTone[report.pilotReadiness]}`}>{report.pilotReadiness}</span></div></section>
    <CoverageMatrix coverage={report.coverage}/>
    <CandidateDirectory candidates={report.candidates} limit={report.limit} offset={report.offset} query={query} totalCount={report.totalCount}/>
  </main>;
}

function CoverageMatrix({ coverage }: { coverage: InstallationMarketplaceSupplyReport["coverage"] }) {
  return <details className="border border-zinc-200 bg-white p-4" open><summary className="flex min-h-11 cursor-pointer items-center font-semibold">Покрытие: регион × компетенция ({coverage.length})</summary><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b"><th className="p-2">Регион</th><th className="p-2">Компетенция</th><th className="p-2 text-right">Активны</th><th className="p-2 text-right">Доступны</th><th className="p-2">Порог / пилот</th><th className="p-2">Статус</th></tr></thead><tbody>{coverage.map((item)=><tr className="border-b border-zinc-100" key={`${item.regionCode}:${item.capability}`}><td className="p-2"><strong>{item.regionNameRu}</strong><details><summary className="mt-1 min-h-11 cursor-pointer text-xs text-blue-700">Исполнители и кандидаты</summary><div className="min-w-64 space-y-1 pb-2 text-xs text-zinc-600"><p><b>ACTIVE:</b> {partnerNames(item.activePartners)}</p><p><b>PENDING:</b> {partnerNames(item.pendingPartners)}</p><p><b>CANDIDATES:</b> {partnerNames(item.candidatePartners)}</p></div></details></td><td className="p-2">{item.capability}</td><td className="p-2 text-right tabular-nums">{item.active}</td><td className="p-2 text-right tabular-nums">{item.available}</td><td className="p-2"><form action={saveInstallationMarketplacePilotConfigurationAction} className="flex items-center gap-2"><input name="regionCode" type="hidden" value={item.regionCode}/><input name="capability" type="hidden" value={item.capability}/><input name="revision" type="hidden" value={item.revision}/><input name="correlationId" type="hidden" value={crypto.randomUUID()}/><input aria-label="Минимум активных исполнителей" className="h-11 w-20 border border-zinc-300 px-2" defaultValue={item.threshold} max={20} min={1} name="threshold" type="number"/><label className="flex min-h-11 items-center gap-2"><input defaultChecked={item.pilotEnabled} name="enabled" type="checkbox"/>Пилот</label><button className="min-h-11 border border-zinc-900 px-3 font-semibold">Сохранить</button></form></td><td className="p-2 font-semibold">{item.readiness ?? "OFF"}</td></tr>)}</tbody></table></div></details>;
}

function CandidateDirectory({ candidates, limit, offset, query, totalCount }: { candidates: InstallationMarketplaceSupplyReport["candidates"]; limit:number; offset:number; query: Record<string, string | string[] | undefined>; totalCount: number }) {
  const currentFilter=typeof query.filter==="string"?query.filter:"all";
  const currentPage=Math.floor(offset/limit)+1;
  const pageHref=(page:number)=>`/admin/retail/installation?section=supply&filter=${encodeURIComponent(currentFilter)}&search=${encodeURIComponent(typeof query.search==="string"?query.search:"")}&page=${page}`;
  return <section className="space-y-4" aria-labelledby="supply-candidates"><div><h2 className="text-xl font-semibold" id="supply-candidates">Кандидаты ({totalCount})</h2><p className="text-sm text-zinc-600">Все активные B2B-компании; readiness и blockers получены из существующего activation-контракта.</p></div><form className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_180px_auto]" method="get"><input name="section" type="hidden" value="supply"/><input className="min-h-11 border border-zinc-300 px-3" defaultValue={typeof query.search==="string"?query.search:""} name="search" placeholder="Компания"/><select className="min-h-11 border border-zinc-300 px-3" defaultValue={currentFilter} name="filter"><option value="all">Все</option><option value="potential">Потенциальные</option><option value="invited">Приглашены</option><option value="started">Начали</option><option value="pending">На проверке</option><option value="active">Активные</option><option value="suspended">Приостановлены</option></select><button className="min-h-11 bg-zinc-900 px-4 font-semibold text-white">Применить</button></form><div className="grid gap-3">{candidates.map((candidate)=><CandidateCard candidate={candidate} key={candidate.companyId}/>)}</div>{totalCount>limit?<nav aria-label="Страницы кандидатов" className="flex items-center justify-between"><a aria-disabled={currentPage===1} className={`inline-flex min-h-11 items-center border px-4 font-semibold ${currentPage===1?"pointer-events-none opacity-40":""}`} href={pageHref(Math.max(1,currentPage-1))}>Назад</a><span className="text-sm text-zinc-600">Страница {currentPage}</span><a aria-disabled={offset+limit>=totalCount} className={`inline-flex min-h-11 items-center border px-4 font-semibold ${offset+limit>=totalCount?"pointer-events-none opacity-40":""}`} href={pageHref(currentPage+1)}>Далее</a></nav>:null}</section>;
}

function CandidateCard({ candidate }: { candidate: InstallationMarketplaceSupplyReport["candidates"][number] }) {
  return <article className="border border-zinc-200 bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{candidate.companyName}</h3><p className="mt-1 text-xs text-zinc-500">{candidate.participationStatus} · {candidate.readinessGroup} · {candidate.availability}</p></div><div className="flex flex-wrap gap-2"><span className="rounded bg-zinc-100 px-2 py-1 text-xs font-semibold">{candidate.missingStepCount} blockers</span>{candidate.invitationStatus?<span className="rounded bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-800">{candidate.invitationStatus}</span>:null}</div></div><div className="mt-3 grid gap-3 text-sm md:grid-cols-3"><Fact label="Компетенции" value={candidate.capabilities.map((item)=>`${item.code}${item.verificationStatus==="verified"?" ✓":""}`).join(", ")||"—"}/><Fact label="Территории" value={candidate.serviceAreas.map((item)=>item.nameRu).join(", ")||"—"}/><Fact label="Требуется" value={candidate.readiness.blockers.join(", ")||"Нет blockers"}/></div><div className="mt-4 flex flex-wrap gap-2"><InvitationControls candidate={candidate}/>{candidate.participationStatus==="PENDING_REVIEW"&&candidate.providerId?<ActivationReview candidate={candidate}/>:null}</div></article>;
}

function InvitationControls({ candidate }: { candidate: InstallationMarketplaceSupplyReport["candidates"][number] }) {
  if(candidate.invitationStatus==="READY_TO_SEND"&&candidate.invitationId&&candidate.invitationRevision!==null)return <form action={sendInstallationMarketplaceInvitationAction}><input name="invitationId" type="hidden" value={candidate.invitationId}/><input name="revision" type="hidden" value={candidate.invitationRevision}/><input name="correlationId" type="hidden" value={crypto.randomUUID()}/><button className="min-h-11 rounded-md bg-emerald-700 px-4 text-sm font-semibold text-white">Отправить приглашение</button></form>;
  if(["SENT","OPENED","PARTNER_STARTED","PARTNER_SUBMITTED","APPROVED","DECLINED"].includes(candidate.invitationStatus??""))return null;
  return <details className="border border-zinc-200 px-2"><summary className="flex min-h-11 cursor-pointer items-center px-2 text-sm font-semibold">Подготовить приглашение</summary><form action={prepareInstallationMarketplaceInvitationAction} className="grid gap-2 pb-3 sm:min-w-[420px]"><input name="companyId" type="hidden" value={candidate.companyId}/><input name="revision" type="hidden" value={candidate.invitationRevision??0}/><input name="correlationId" type="hidden" value={crypto.randomUUID()}/><div className="border-l-4 border-blue-500 bg-blue-50 p-3 text-sm"><strong>Предпросмотр ценности</strong><p className="mt-1">Новые заявки на монтаж от клиентов NSD, публичный профиль и проверенные отзывы. Партнёр сам выбирает компетенции и регионы; участие добровольное, объём заявок не гарантируется.</p></div><label className="grid gap-1 text-sm"><span>Язык</span><select className="min-h-11 border border-zinc-300 px-3" defaultValue={candidate.invitationLocale??"ru"} name="locale"><option value="ru">RU</option><option value="ro">RO</option></select></label><label className="flex min-h-11 items-center gap-2 text-sm"><input defaultChecked name="email" type="checkbox"/>Email (In-app обязателен)</label><label className="grid gap-1 text-sm"><span>Срок, необязательно</span><input className="min-h-11 border border-zinc-300 px-3" name="expiresAt" type="datetime-local"/></label><div className="flex flex-wrap gap-2"><button className="min-h-11 border border-zinc-900 px-3 text-sm font-semibold" name="command" value="INVITATION_DRAFT">Сохранить dry-run</button><button className="min-h-11 bg-zinc-900 px-3 text-sm font-semibold text-white" name="command" value="READY_TO_SEND">Готово к отправке</button></div></form></details>;
}

function ActivationReview({ candidate }: { candidate: InstallationMarketplaceSupplyReport["candidates"][number] }) {return <details className="border border-zinc-200 px-2"><summary className="flex min-h-11 cursor-pointer items-center px-2 text-sm font-semibold">Решение по заявке</summary><form action={reviewInstallationMarketplaceActivationAction} className="grid gap-2 pb-3 sm:min-w-96"><input name="providerId" type="hidden" value={candidate.providerId??""}/><input name="revision" type="hidden" value={candidate.providerRevision}/><select className="min-h-11 border border-zinc-300 px-3" name="command"><option value="APPROVE">Одобрить</option><option value="REJECT">Отклонить</option></select><select className="min-h-11 border border-zinc-300 px-3" name="rejectionReason"><option value="">Причина только для отказа</option><option value="INCOMPLETE_PROFILE">Неполный профиль</option><option value="INSUFFICIENT_CAPABILITY">Недостаточно компетенций</option><option value="SERVICE_AREA_INVALID">Некорректная территория</option><option value="COMPLIANCE">Соответствие</option><option value="QUALITY_CONCERN">Риск качества</option><option value="OTHER">Другое</option></select><textarea className="min-h-20 border border-zinc-300 p-3" maxLength={500} name="note" placeholder="Комментарий"/><button className="min-h-11 bg-zinc-900 px-4 text-sm font-semibold text-white">Сохранить решение</button></form></details>}
function Metric({label,value}:{label:string;value:number}){return <div className="border border-zinc-200 bg-white p-4"><strong className="text-2xl tabular-nums">{value}</strong><p className="mt-1 text-xs text-zinc-500">{label}</p></div>}
function Fact({label,value}:{label:string;value:string}){return <div><strong className="text-xs uppercase tracking-wide text-zinc-500">{label}</strong><p className="mt-1 break-words">{value}</p></div>}
function partnerNames(partners:ReadonlyArray<{companyId:string;companyName:string}>){return partners.map((partner)=>partner.companyName).join(", ")||"—"}
