import {
  BookOpen,
  Boxes,
  Building2,
  Calculator,
  ClipboardList,
  Columns3,
  FileText,
  FolderKanban,
  Gauge,
  Gift,
  GraduationCap,
  Landmark,
  Layers3,
  LifeBuoy,
  Lightbulb,
  ListChecks,
  Megaphone,
  SearchCheck,
  ShoppingCart,
  Star,
  UserRound,
  WandSparkles,
  Wrench,
} from "lucide-react";

import type { WorkspaceCapabilityKey } from "../services";

export const partnerNavigationIcons = {
  dashboard: Gauge,
  catalog: Boxes,
  opportunities: Lightbulb,
  offers: Megaphone,
  cart: ShoppingCart,
  purchasing_lists: Star,
  purchase_templates: Layers3,
  comparison: Columns3,
  solution_selection: SearchCheck,
  projects: FolderKanban,
  reservations: ClipboardList,
  proposals: Calculator,
  customers: Building2,
  nomenclature: ClipboardList,
  proposal_generator: WandSparkles,
  orders: ListChecks,
  installation_marketplace: Wrench,
  installation_profile: UserRound,
  expertise_lab: BookOpen,
  expertise_academy: GraduationCap,
  finance: Landmark,
  documents: FileText,
  warranty: LifeBuoy,
  support: LifeBuoy,
  knowledge_base: BookOpen,
  loyalty_affiliate: Gift,
  loyalty_bonus: Gift,
  company: Building2,
} satisfies Record<WorkspaceCapabilityKey, typeof Gauge>;
