import { describe, expect, it, vi } from "vitest";
vi.mock("server-only",()=>({}));
import { ChunkedStockSyncService, type StockSyncState, type StockSyncStore } from "../chunked-stock-sync";
import type { StockBalanceProvider, SupplierArrivalProvider } from "../../providers/one-c";

describe("ChunkedStockSyncService",()=>{
  it("preserves the published snapshot when a middle scan fails",async()=>{const store=fixture(),provider=providerFixture();provider.fetchBalances.mockRejectedValueOnce(new Error("failed"));await new ChunkedStockSyncService(provider,supplierFixture(),store).continue(syncId);expect(store.publish).not.toHaveBeenCalled();expect(store.state.status).toBe("failed");});
  it("publishes only after stock, supplier balance and supplier documents complete",async()=>{const store=fixture();const service=new ChunkedStockSyncService(providerFixture(),supplierFixture(),store);const first=await service.continue(syncId);expect(first.pages).toBe(5);expect(store.publish).not.toHaveBeenCalled();const second=await service.continue(syncId);expect(second.pages).toBe(1);expect(store.publish).toHaveBeenCalledOnce();expect(store.state.status).toBe("succeeded");});
  it("duplicate workers cannot process one checkpoint",async()=>{const store=fixture();store.claim.mockResolvedValueOnce(false);const provider=providerFixture();await new ChunkedStockSyncService(provider,supplierFixture(),store).continue(syncId);expect(provider.fetchWarehouses).not.toHaveBeenCalled();});
});

function providerFixture(){return{fetchWarehouses:vi.fn(async()=>({items:[],rowCount:0})),fetchBalances:vi.fn(async()=>({items:[],rowCount:0}))}satisfies StockBalanceProvider;}
function supplierFixture(){return{fetchSupplierBalances:vi.fn(async()=>({items:[],rowCount:0,received:0,groups:0,excluded:0})),fetchSupplierOrderDocuments:vi.fn(async()=>[])}satisfies SupplierArrivalProvider;}
function fixture(){const state:StockSyncState={status:"queued",activeSyncId:syncId,lastFailedSyncId:null,snapshotTime:"2026-07-12T12:00:00Z",currentStage:"warehouse_scan",nextSkip:0,pageSize:500,pagesProcessed:0,physicalRows:0,reservedRows:0,incomingRows:0,warehousesLoaded:0,productsMatched:0,productsUnmatched:0,rowsPublished:0,rowsDeactivated:0,scanComplete:false,startedAt:null,lastSuccessfulSyncAt:null,errorCategory:null,failedStage:null,safeError:null,failedPage:null,updatedAt:"2026-07-12T12:00:00Z"};const store={state,start:vi.fn(async()=>({state,started:true})),getState:vi.fn(async()=>state),claim:vi.fn(async()=>true),release:vi.fn(async()=>undefined),stageWarehouses:vi.fn(async()=>0),stageBalances:vi.fn(async()=>0),stageSupplierBalances:vi.fn(async()=>undefined),listSupplierOrderRefs:vi.fn(async()=>[]),stageSupplierDocuments:vi.fn(async()=>undefined),checkpoint:vi.fn(async(_id,input)=>{state.status="running";state.currentStage=input.stage;state.nextSkip=input.nextSkip;state.pagesProcessed++;state.scanComplete=input.complete??state.scanComplete;}),publish:vi.fn(async()=>{state.status="succeeded";state.activeSyncId=null;state.currentStage="completed";}),fail:vi.fn(async(_id,stage,page)=>{state.status="failed";state.failedStage=stage;state.failedPage=page;state.activeSyncId=null;}),failLaunch:vi.fn(async()=>undefined)}satisfies StockSyncStore&{state:StockSyncState};return store;}
const syncId="11111111-1111-4111-8111-111111111111";
