import Link from "next/link";
import { notFound } from "next/navigation";
import { getPurchasingListAction } from "@/src/modules/purchasing-lists/actions";
import { PurchasingListActions, PurchasingListEditor } from "@/src/modules/purchasing-lists/components";
import { SaveAsPurchaseTemplateButton } from "@/src/modules/purchase-templates/components";
import { procurementCopy } from "@/src/modules/partner-locale";
import { getPartnerLocale } from "@/src/modules/partner-locale/server";

export default async function PurchasingListDetailPage({ params }: { params: Promise<{ listId: string }> }) { const [{ listId }, locale] = await Promise.all([params, getPartnerLocale()]); const copy = procurementCopy(locale); const result = await getPurchasingListAction(listId); if (!result.success) { if (result.errorCode === "NOT_FOUND") notFound(); return <p className="rounded-md border border-rose-200 bg-rose-50 p-5 text-sm text-rose-800">{copy.listUnavailable}</p>; } return <div className="mx-auto max-w-7xl space-y-5"><header><Link className="text-sm font-semibold text-emerald-700" href="/cabinet/purchasing-lists">← {copy.favorites}</Link><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><h1 className="text-2xl font-semibold">{result.data.name}</h1>{result.data.archivedAt ? <span className="rounded bg-zinc-200 px-2 py-1 text-xs font-semibold">{copy.archive}</span> : null}</div><div className="flex flex-wrap gap-2"><SaveAsPurchaseTemplateButton source={{ type: "purchasing_list", id: result.data.id }} /><PurchasingListActions archived={Boolean(result.data.archivedAt)} canManage={result.data.canManage} listId={result.data.id} name={result.data.name} revision={result.data.revision} /></div></div><p className="mt-1 text-sm text-zinc-500">{copy.currentCommercialHint}</p></header><PurchasingListEditor initial={result.data} /></div>; }
