import Link from "next/link";
import { notFound } from "next/navigation";
import { Download, MessageSquareText, Paperclip } from "lucide-react";
import { cancelCustomerServiceRequestAction } from "@/src/modules/final-customer/actions";
import { CustomerServiceReplyForm } from "@/src/modules/final-customer/components";
import { createFinalCustomerService, getFinalCustomerContext } from "@/src/modules/final-customer/server";
import { getFinalCustomerLocale } from "@/src/modules/final-customer/locale";
import { customerDate, serviceStatusLabel, serviceTypeLabel } from "@/src/modules/final-customer/presentation";
import { customerServiceCancelAllowed, customerServiceReplyAllowed } from "@/src/modules/final-customer/service-lifecycle";
import { OperationalTimeline } from "@/src/modules/cabinet-experience/components";

export default async function CustomerServiceRequestPage({ params }: { params: Promise<{ requestId: string }> }) {
  const [{ requestId }, context, locale] = await Promise.all([params, getFinalCustomerContext(), getFinalCustomerLocale()]);
  const request = await createFinalCustomerService().serviceRequest(context.account, requestId); if (!request) notFound();
  const ro = locale === "ro"; const replyAllowed = customerServiceReplyAllowed(request.status);
  return <main className="mx-auto max-w-3xl space-y-5 px-4 py-6 sm:py-8">
    <header><Link className="inline-flex min-h-11 items-center text-sm font-semibold text-emerald-700" href="/account/service">← {ro ? "Service" : "Сервис"}</Link><div className="mt-1 flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs text-zinc-500">{request.number}</p><h1 className="mt-1 text-2xl font-semibold">{request.subject}</h1><p className="mt-1 text-sm text-zinc-500">{serviceTypeLabel(request.type, locale)} · {customerDate(request.createdAt, locale)}</p></div><span className={request.status === "NEED_INFO" ? "rounded-full bg-amber-100 px-3 py-1 text-sm font-semibold text-amber-900" : "rounded-full bg-zinc-100 px-3 py-1 text-sm text-zinc-700"}>{serviceStatusLabel(request.status, locale)}</span></div></header>
    {request.status === "NEED_INFO" ? <section className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><strong>{ro ? "Este necesar răspunsul dvs." : "Требуется ваш ответ."}</strong> {ro ? "Consultați ultimul mesaj Novotech și completați informațiile." : "Прочитайте последнее сообщение Novotech и дополните информацию."}</section> : null}
    <section className="space-y-3"><div className="flex items-center gap-2"><MessageSquareText aria-hidden className="size-5 text-emerald-700" /><h2 className="font-semibold">{ro ? "Conversație" : "Переписка"}</h2></div>{request.messages.length ? <ol className="space-y-3">{request.messages.map((message) => <li className={`max-w-[92%] rounded-xl border p-4 text-sm ${message.authorType === "CUSTOMER" ? "ml-auto border-emerald-200 bg-emerald-50" : "border-zinc-200 bg-white"}`} key={message.id}><p className="text-xs font-semibold text-zinc-500">{message.authorType === "CUSTOMER" ? (ro ? "Dvs." : "Вы") : "Novotech"} · {customerDate(message.createdAt, locale)}</p><p className="mt-2 whitespace-pre-wrap leading-6">{message.body}</p></li>)}</ol> : <p className="text-sm text-zinc-500">{ro ? "Nu există încă mesaje." : "Сообщений пока нет."}</p>}</section>
    {replyAllowed ? <CustomerServiceReplyForm expectedVersion={request.version} locale={locale} requestId={request.id} /> : <p className="rounded-xl border border-zinc-200 bg-white p-4 text-sm text-zinc-600">{ro ? "Pentru ajutor suplimentar creați o solicitare nouă." : "Для дополнительной помощи создайте новое обращение."}</p>}
    <details className="rounded-xl border border-zinc-200 bg-white p-5"><summary className="cursor-pointer font-semibold">{ro ? "Solicitarea inițială" : "Исходное обращение"}</summary><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{request.description}</p><p className="mt-3 text-xs text-zinc-500">{ro ? "Contact preferat" : "Предпочтительная связь"}: {request.preferredContact === "EMAIL" ? "Email" : (ro ? "Telefon" : "Телефон")}</p></details>
    {request.attachments.length ? <section className="space-y-3"><div className="flex items-center gap-2"><Paperclip aria-hidden className="size-5 text-emerald-700" /><h2 className="font-semibold">{ro ? "Fișiere" : "Файлы"}</h2></div><ul className="grid gap-2 sm:grid-cols-2">{request.attachments.map((attachment) => <li key={attachment.id}><a className="flex min-h-11 items-center gap-2 rounded-lg border border-zinc-200 bg-white px-3 text-sm font-medium" href={`/api/customer-service/attachments/${attachment.id}`}><Download aria-hidden className="size-4" /><span className="truncate">{attachment.fileName}</span></a></li>)}</ul></section> : null}
    <section className="rounded-xl border border-zinc-200 bg-white p-5"><h2 className="mb-4 font-semibold">{ro ? "Istoric" : "История"}</h2><OperationalTimeline items={request.timeline.map((event) => ({ id: event.id, label: timelineLabel(event.eventType, event.toStatus, locale), date: customerDate(event.createdAt, locale) }))} /></section>
    <div className="flex flex-wrap gap-3">{request.orderId ? <Link className="inline-flex min-h-11 items-center text-sm font-semibold text-emerald-700" href={`/account/orders/${request.orderId}`}>{ro ? "Comanda asociată" : "Связанный заказ"}</Link> : null}{customerServiceCancelAllowed(request.status) ? <form action={cancelCustomerServiceRequestAction}><input name="requestId" type="hidden" value={request.id} /><input name="expectedVersion" type="hidden" value={request.version} /><button className="min-h-11 rounded-lg border border-red-200 px-4 text-sm font-semibold text-red-700">{ro ? "Anulează solicitarea" : "Отменить обращение"}</button></form> : null}</div>
  </main>;
}
function timelineLabel(eventType: string, status: Parameters<typeof serviceStatusLabel>[0] | null, locale: "ru" | "ro") { const ro = locale === "ro"; if (eventType.includes("CREATED")) return ro ? "Solicitare primită" : "Обращение получено"; if (eventType.includes("CUSTOMER_REPLIED")) return ro ? "Ați răspuns" : "Вы ответили"; if (eventType.includes("REPLY_FROM_NOVOTECH") || eventType === "NOVOTECH_REPLIED") return ro ? "Novotech a răspuns" : "Novotech ответил"; if (eventType.includes("STATUS") && status) return `${ro ? "Statut" : "Статус"}: ${serviceStatusLabel(status, locale)}`; return ro ? "Solicitare actualizată" : "Обращение обновлено"; }
