import type { PublicLocale } from "@/src/modules/public-locale";

export const accessContextCopy = {
  ru: {
    brand: "Novotech Systems Distribution",
    authTitle: "Вход в личный кабинет",
    authDescription: "Используйте данные своей учётной записи.",
    businessLabel: "Электронная почта и пароль",
    businessHint: "",
    divider: "или",
    customerAction: "Войти по номеру телефона",
    customerHint: "",
    customerTitle: "Личный кабинет",
    customerDescription: "Быстрый вход по номеру телефона",
    businessAction: "Войти с email и паролем",
    notActiveTitle: "Ваш личный кабинет NSD ещё не активирован.",
    notActiveBody: "Личный кабинет активируется автоматически после первой покупки. После покупки вы сможете:",
    notActiveBenefits: ["Отслеживать заказы", "Видеть приобретённое оборудование", "Контролировать гарантию", "Получать документы", "Обращаться в сервис"],
    catalogAction: "Перейти в каталог",
    customerBlockedTitle: "Доступ к личному кабинету ограничен",
    customerBlockedBody: "Для проверки доступа обратитесь в службу поддержки NSD.",
    businessStateTitle: "Рабочий доступ пока недоступен",
    businessStateBody: "Ваша учётная запись подтверждена, но активное рабочее пространство партнёра или агента не найдено.",
    selectTitle: "Выберите рабочее пространство",
    selectDescription: "Доступ проверяется сервером при каждом выборе.",
    partner: "Партнёр",
    agent: "Агент",
    open: "Открыть",
    unavailable: "Это рабочее пространство больше недоступно. Выберите актуальный вариант.",
    signOut: "Выйти",
    ru: "RU",
    ro: "RO",
  },
  ro: {
    brand: "Novotech Systems Distribution",
    authTitle: "Autentificare în contul personal",
    authDescription: "Folosiți datele contului dumneavoastră.",
    businessLabel: "E-mail și parolă",
    businessHint: "",
    divider: "sau",
    customerAction: "Autentificare cu numărul de telefon",
    customerHint: "",
    customerTitle: "Cont personal",
    customerDescription: "Autentificare rapidă cu numărul de telefon",
    businessAction: "Autentificare cu e-mail și parolă",
    notActiveTitle: "Contul dumneavoastră personal NSD nu este încă activat.",
    notActiveBody: "Contul personal se activează automat după prima achiziție. După cumpărare veți putea:",
    notActiveBenefits: ["Urmări comenzile", "Vedea echipamentele achiziționate", "Urmări garanția", "Obține documentele", "Solicita servicii"],
    catalogAction: "Deschide catalogul",
    customerBlockedTitle: "Accesul la contul personal este restricționat",
    customerBlockedBody: "Pentru verificarea accesului, contactați serviciul de asistență NSD.",
    businessStateTitle: "Accesul de lucru nu este încă disponibil",
    businessStateBody: "Contul este autentificat, dar nu a fost găsit niciun spațiu de lucru activ de partener sau agent.",
    selectTitle: "Alegeți spațiul de lucru",
    selectDescription: "Accesul este verificat pe server la fiecare alegere.",
    partner: "Partener",
    agent: "Agent",
    open: "Deschide",
    unavailable: "Acest spațiu de lucru nu mai este disponibil. Alegeți o opțiune actuală.",
    signOut: "Ieșire",
    ru: "RU",
    ro: "RO",
  },
} as const satisfies Record<PublicLocale, Record<string, string | readonly string[]>>;
