import type { PublicLocale } from "@/src/modules/public-locale";

export const accessContextCopy = {
  ru: {
    brand: "NSD",
    authTitle: "Вход в NSD",
    authDescription: "Выберите способ входа, соответствующий вашей рабочей роли.",
    businessLabel: "Партнёр / Агент",
    businessHint: "Вход по электронной почте и паролю",
    divider: "или",
    customerAction: "Войти по номеру телефона",
    customerHint: "Для финальных покупателей",
    customerTitle: "Личный кабинет",
    customerDescription: "Быстрый вход по номеру телефона",
    businessAction: "Войти как партнёр или агент",
    notActiveTitle: "Ваш личный кабинет NSD ещё не активирован.",
    notActiveBody: "Личный кабинет создаётся после первой покупки. После покупки вы сможете отслеживать заказы, оборудование, гарантию, документы и сервис.",
    catalogAction: "Перейти в каталог",
    customerBlockedTitle: "Доступ к личному кабинету ограничен",
    customerBlockedBody: "Для проверки доступа обратитесь в службу поддержки NSD.",
    businessStateTitle: "Рабочий доступ пока недоступен",
    businessStateBody: "Ваша учётная запись подтверждена, но активное рабочее пространство партнёра или агента не найдено.",
    selectTitle: "Выберите рабочее пространство",
    selectDescription: "Доступ проверяется сервером при каждом выборе.",
    partner: "Партнёр",
    agent: "Агент",
    open: "Открыть",
    unavailable: "Это рабочее пространство больше недоступно. Выберите актуальный вариант.",
    signOut: "Выйти",
    ru: "RU",
    ro: "RO",
  },
  ro: {
    brand: "NSD",
    authTitle: "Autentificare NSD",
    authDescription: "Alegeți metoda de autentificare corespunzătoare rolului dumneavoastră.",
    businessLabel: "Partener / Agent",
    businessHint: "Autentificare cu e-mail și parolă",
    divider: "sau",
    customerAction: "Autentificare cu numărul de telefon",
    customerHint: "Pentru clienții finali",
    customerTitle: "Cont personal",
    customerDescription: "Autentificare rapidă cu numărul de telefon",
    businessAction: "Autentificare ca partener sau agent",
    notActiveTitle: "Contul dumneavoastră personal NSD nu este încă activat.",
    notActiveBody: "Contul personal este creat după prima achiziție. După cumpărare veți putea urmări comenzile, echipamentele, garanția, documentele și serviciile.",
    catalogAction: "Deschide catalogul",
    customerBlockedTitle: "Accesul la contul personal este restricționat",
    customerBlockedBody: "Pentru verificarea accesului, contactați serviciul de asistență NSD.",
    businessStateTitle: "Accesul de lucru nu este încă disponibil",
    businessStateBody: "Contul este autentificat, dar nu a fost găsit niciun spațiu de lucru activ de partener sau agent.",
    selectTitle: "Alegeți spațiul de lucru",
    selectDescription: "Accesul este verificat pe server la fiecare alegere.",
    partner: "Partener",
    agent: "Agent",
    open: "Deschide",
    unavailable: "Acest spațiu de lucru nu mai este disponibil. Alegeți o opțiune actuală.",
    signOut: "Ieșire",
    ru: "RU",
    ro: "RO",
  },
} as const satisfies Record<PublicLocale, Record<string, string>>;
