"use client";

import { Plus, Save, Search } from "lucide-react";
import { useState, useTransition } from "react";
import { ProductThumbnail } from "../../catalog/components/ProductThumbnail";
import { CCTV_OBJECT_TYPES, type CctvCameraCandidateSearchRow, type CctvCameraPoolAdminRow } from "../../cctv-calculation";
import { actionClassName, ActionFeedback } from "../../platform-ui";
import { searchCctvCameraCandidatesAction, upsertCctvCameraPoolAction } from "../actions";

const objectLabels: Record<string,string> = { apartment:"Квартира",house:"Частный дом",office:"Офис",retail:"Магазин / Retail",warehouse:"Склад",industrial:"Промышленный объект",horeca:"HoReCa",other:"Общий пул" };
const priorityLabels = { high:"Высокий",normal:"Обычный",low:"Низкий" } as const;

export function AdminCctvCameraPools({ initialRows }: { initialRows: CctvCameraPoolAdminRow[] }) {
  const [rows,setRows]=useState(initialRows); const [objectType,setObjectType]=useState("warehouse");
  const [placement,setPlacement]=useState<"indoor"|"outdoor">("indoor");
  const visible=rows.filter((row)=>row.objectType===objectType&&row.placement===placement);
  const saveRow=(saved:CctvCameraPoolAdminRow)=>setRows((current)=>current.some((row)=>row.candidateId===saved.candidateId)
    ?current.map((row)=>row.candidateId===saved.candidateId?saved:row):[...current,saved]);
  return <section className="space-y-4 rounded-md border border-zinc-200 bg-white p-4">
    <header><h2 className="font-semibold">Пулы выбора камер</h2><p className="mt-1 text-sm text-zinc-600">Только подтверждённые камеры. Техническая совместимость проверяется до коммерческого ранжирования.</p></header>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Тип объекта<select className="mt-1 min-h-11 w-full rounded-md border border-zinc-300 bg-white px-3" value={objectType} onChange={(event)=>setObjectType(event.target.value)}>{CCTV_OBJECT_TYPES.map((value)=><option key={value} value={value}>{objectLabels[value]}</option>)}</select></label><div><span className="text-sm font-medium">Размещение</span><div className="mt-1 grid grid-cols-2"><button aria-pressed={placement==="indoor"} className={`min-h-11 border px-3 text-sm ${placement==="indoor"?"border-emerald-700 bg-emerald-50":"border-zinc-300"}`} onClick={()=>setPlacement("indoor")} type="button">В помещении</button><button aria-pressed={placement==="outdoor"} className={`min-h-11 border px-3 text-sm ${placement==="outdoor"?"border-emerald-700 bg-emerald-50":"border-zinc-300"}`} onClick={()=>setPlacement("outdoor")} type="button">На улице</button></div></div></div>
    <CandidateSearch objectType={objectType} placement={placement} onSaved={saveRow}/>
    {visible.length ? <div className="space-y-3">{visible.map((row)=><CandidateEditor key={row.candidateId} row={row} onSaved={saveRow}/>)}</div>:<p className="border-l-4 border-amber-500 bg-amber-50 px-4 py-3 text-sm">Пул не настроен. Автоматический выбор для этого объекта и размещения останется нерешённым.</p>}
  </section>;
}

function CandidateSearch({objectType,placement,onSaved}:{objectType:string;placement:"indoor"|"outdoor";onSaved:(row:CctvCameraPoolAdminRow)=>void}) {
  const [query,setQuery]=useState(""); const [results,setResults]=useState<CctvCameraCandidateSearchRow[]>([]);
  const [message,setMessage]=useState<string|null>(null); const [pending,startTransition]=useTransition();
  const runSearch=()=>startTransition(async()=>{const result=await searchCctvCameraCandidatesAction({query,objectType,placement});setMessage(result.message);setResults(result.success?result.data:[]);});
  return <div className="space-y-3 border-y border-zinc-200 py-4"><div className="flex flex-col gap-2 sm:flex-row"><label className="min-w-0 flex-1 text-sm font-medium">Добавить камеру<input className="mt-1 min-h-11 w-full rounded-md border border-zinc-300 px-3" onChange={(event)=>setQuery(event.target.value)} onKeyDown={(event)=>{if(event.key==="Enter"){event.preventDefault();runSearch();}}} placeholder="SKU или модель" value={query}/></label><button className={`${actionClassName.secondary} sm:self-end`} disabled={pending||query.trim().length<2} onClick={runSearch} type="button"><Search className="size-4"/>Найти</button></div>
    {results.length>0&&<div className="grid gap-2 lg:grid-cols-2">{results.map((row)=><article className="flex min-w-0 gap-3 rounded-md border border-zinc-200 p-3" key={row.productId}><div className="relative size-16 shrink-0 overflow-hidden rounded border border-zinc-200 bg-zinc-50"><ProductThumbnail alt={row.name} sizes="64px" src={row.imageUrl} variant="sm"/></div><div className="min-w-0 flex-1"><strong className="block truncate" title={row.name}>{row.sku} · {row.name}</strong><p className="mt-1 text-xs text-zinc-600">{row.resolutionMp} Мп · остаток {row.availableStock} · продажи 90 дней {row.recentSalesQty}</p><p className="text-xs text-zinc-600">{row.retailPriceAmount==null?"RETAIL не опубликован":`${row.retailPriceAmount.toFixed(2)} ${row.retailPriceCurrency}`}</p></div><button aria-label={`Добавить ${row.sku} в пул`} className="inline-flex size-11 shrink-0 items-center justify-center rounded-md border border-zinc-300 text-zinc-700 hover:bg-zinc-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-600 disabled:opacity-50" disabled={pending||row.alreadyInPool} onClick={()=>startTransition(async()=>{const result=await upsertCctvCameraPoolAction({objectType,placement,productId:row.productId,manualPriority:"normal",enabled:true,notes:"",expectedVersion:null});setMessage(result.message);if(result.success){onSaved(result.data);setResults((current)=>current.map((item)=>item.productId===row.productId?{...item,alreadyInPool:true}:item));}})} title={row.alreadyInPool?"Уже в пуле":"Добавить в пул"} type="button"><Plus className="size-4"/></button></article>)}</div>}
    {message&&<ActionFeedback kind={message.includes("найдены")||message.includes("сохранён")?"success":"error"} message={message}/>}</div>;
}

function CandidateEditor({row,onSaved}:{row:CctvCameraPoolAdminRow;onSaved:(row:CctvCameraPoolAdminRow)=>void}) {
  const [priority,setPriority]=useState(row.manualPriority); const [enabled,setEnabled]=useState(row.enabled);
  const [notes,setNotes]=useState(row.notes??""); const [message,setMessage]=useState<string|null>(null); const [pending,startTransition]=useTransition();
  const diagnostics=[!row.technicalVerified&&"Нет подтверждённых метаданных",!row.publicPublished&&"Не опубликован в Public Retail",row.availableStock<=0&&"Нет доступного остатка"].filter(Boolean);
  return <article className="grid gap-3 rounded-md border border-zinc-200 p-3 lg:grid-cols-[minmax(0,1fr)_10rem_8rem_auto] lg:items-end"><div><strong>{row.sku} · {row.name}</strong><p className="mt-1 text-xs text-zinc-600">{row.resolutionMp} Мп · остаток {row.availableStock} · продажи 90 дней {row.recentSalesQty}</p><p className={`mt-1 text-xs ${diagnostics.length?"text-amber-700":"text-emerald-700"}`}>{diagnostics.join(" · ")||"Технически подтверждён и доступен"}</p><input aria-label={`Примечание ${row.sku}`} className="mt-2 min-h-11 w-full rounded-md border border-zinc-300 px-3 text-sm" maxLength={1000} onChange={(e)=>setNotes(e.target.value)} placeholder="Примечание" value={notes}/></div><label className="text-xs font-medium">Приоритет<select className="mt-1 min-h-11 w-full rounded-md border border-zinc-300 bg-white px-2 text-sm" value={priority} onChange={(e)=>setPriority(e.target.value as typeof priority)}>{Object.entries(priorityLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="flex min-h-11 items-center gap-2 text-sm"><input checked={enabled} onChange={(e)=>setEnabled(e.target.checked)} type="checkbox"/>Включён</label><button className={actionClassName.secondary} disabled={pending} onClick={()=>startTransition(async()=>{const result=await upsertCctvCameraPoolAction({objectType:row.objectType,placement:row.placement,productId:row.productId,manualPriority:priority,enabled,notes,expectedVersion:row.version});setMessage(result.message);if(result.success)onSaved(result.data);})} type="button"><Save className="size-4"/>Сохранить</button>{message&&<div className="lg:col-span-4"><ActionFeedback kind={message==="Кандидат камеры сохранён."?"success":"error"} message={message}/></div>}</article>;
}
