import Image from "next/image";

import { ProductLineThumbnail } from "../../catalog/components/ProductLineThumbnail";
import type { CustomerProposalDto } from "../types";

export function ProposalDocument({ proposal }: { proposal: CustomerProposalDto }) {
  const settings = proposal.settings;
  return <article className="mx-auto min-h-[297mm] w-full max-w-[210mm] bg-white px-5 py-7 text-zinc-800 shadow-sm sm:px-10 sm:py-10">
    <header className="flex flex-col justify-between gap-6 border-b-2 border-emerald-700 pb-6 sm:flex-row">
      <div className="flex gap-3">{settings.showPartnerLogo && proposal.branding.logoUrl && <Image alt="" className="size-14 object-contain" height={56} referrerPolicy="no-referrer" src={proposal.branding.logoUrl} unoptimized width={56} />}<div><p className="text-xl font-bold text-emerald-800">{proposal.branding.companyName}</p>{proposal.branding.legalName && <p className="mt-1 text-xs text-zinc-500">{proposal.branding.legalName}</p>}<BrandingLines proposal={proposal} /></div></div>
      <div className="sm:text-right"><h1 className="text-2xl font-semibold text-zinc-950">{settings.title}</h1><p className="mt-3 font-mono text-sm font-semibold">{proposal.estimateNumber}</p><p className="mt-1 text-xs text-zinc-500">{formatDate(proposal.generatedForDate)}</p></div>
    </header>
    <section className="grid gap-5 border-b border-zinc-200 py-6 sm:grid-cols-2"><div><Label>Получатель</Label><p className="mt-1 font-semibold text-zinc-950">{proposal.customerName || "Не указан"}</p>{proposal.projectName && <p className="mt-1 text-sm text-zinc-600">{proposal.projectName}</p>}</div>{settings.introduction && <p className="text-sm leading-6 text-zinc-600">{settings.introduction}</p>}</section>
    <div className="space-y-7 py-6">{proposal.sections.map((section) => <section key={section.name}><h2 className="mb-3 text-base font-semibold text-emerald-800">{section.name}</h2><div className="overflow-x-auto"><table className="w-full min-w-[620px] table-fixed border-collapse text-xs"><thead><tr className="bg-emerald-50 text-left text-zinc-700"><th className="w-9 px-2 py-2">№</th>{settings.showProductImages && <th className="w-14 px-1 py-2"><span className="sr-only">Изображение</span></th>}<th className="px-2 py-2">Наименование</th><th className="w-24 px-2 py-2 text-right">Количество</th>{settings.showUnitPrice && <th className="w-28 px-2 py-2 text-right">Цена</th>}{settings.showLineDiscount && <th className="w-20 px-2 py-2 text-right">Скидка</th>}<th className="w-28 px-2 py-2 text-right">Сумма</th></tr></thead><tbody>{section.lines.map((line) => <tr className="border-b border-zinc-200 align-top" key={`${section.name}-${line.position}`}><td className="px-2 py-3 text-zinc-500">{line.position}</td>{settings.showProductImages && <td className="px-1 py-2">{isProductProposalLine(line) ? <ProductLineThumbnail imageUrl={line.imageUrl} productName={line.description} size="compact" /> : null}</td>}<td className="px-2 py-3"><p className="font-medium text-zinc-950">{line.description}</p>{settings.showSku && line.sku && <p className="mt-1 font-mono text-[10px] text-zinc-500">SKU {line.sku}</p>}</td><td className="px-2 py-3 text-right">{formatNumber(line.quantity)} {line.unitLabel}</td>{settings.showUnitPrice && <td className="px-2 py-3 text-right">{money(line.unitPrice, proposal.currencyCode)}</td>}{settings.showLineDiscount && <td className="px-2 py-3 text-right">{line.lineDiscountPercent ? `${formatNumber(line.lineDiscountPercent)}%` : "—"}</td>}<td className="px-2 py-3 text-right font-semibold">{money(line.lineTotal, proposal.currencyCode)}</td></tr>)}</tbody></table></div>{settings.showSectionSubtotals && <p className="mt-3 text-right text-sm font-semibold">Итого по разделу: {money(section.subtotal, proposal.currencyCode)}</p>}</section>)}</div>
    {proposal.charges.length > 0 && <section className="border-t border-zinc-200 py-5"><h2 className="font-semibold text-emerald-800">Дополнительные работы и услуги</h2>{proposal.charges.map((charge) => <div className="mt-2 flex justify-between gap-4 text-sm" key={charge.description}><span>{charge.description}</span><strong>{money(charge.amount, proposal.currencyCode)}</strong></div>)}</section>}
    <section className="ml-auto w-full max-w-sm border-y-2 border-emerald-700 py-4"><Total label="Подытог" value={money(proposal.totals.subtotal, proposal.currencyCode)} />{proposal.totals.discounts > 0 && <Total label="Скидки" value={`− ${money(proposal.totals.discounts, proposal.currencyCode)}`} />}{proposal.totals.charges > 0 && <Total label="Дополнительные услуги" value={money(proposal.totals.charges, proposal.currencyCode)} />}{settings.showVatBreakdown && <><Total label="Без НДС" value={money(proposal.totals.totalExcludingVat, proposal.currencyCode)} /><Total label="НДС" value={money(proposal.totals.vat, proposal.currencyCode)} /></>}<div className="mt-3 flex justify-between gap-4 text-lg font-bold text-emerald-800"><span>ИТОГО</span><span>{money(proposal.totals.total, proposal.currencyCode)}</span></div></section>
    <Terms proposal={proposal} />
    <footer className="mt-8 border-t border-zinc-200 pt-4 text-xs text-zinc-500">{settings.footerNote || proposal.branding.companyName}</footer>
  </article>;
}

function BrandingLines({ proposal }: { proposal: CustomerProposalDto }) { const values = [proposal.branding.address, proposal.branding.fiscalInformation, proposal.branding.phone, proposal.branding.email, proposal.branding.website].filter(Boolean); return <div className="mt-2 space-y-0.5 text-xs text-zinc-500">{values.map((value) => <p key={value}>{value}</p>)}</div>; }
function Terms({ proposal }: { proposal: CustomerProposalDto }) { const s = proposal.settings; const terms = [["Поставка", s.deliveryTerms], ["Оплата", s.paymentTerms], ["Гарантия", s.warrantyTerms], ["Срок действия", s.validityText], ["Монтаж", s.installationNotes], ["Исключения", s.exclusions], ["Примечание", s.customerNote]].filter(([, value]) => value); return terms.length ? <section className="mt-8 break-inside-avoid"><h2 className="text-base font-semibold text-emerald-800">Условия предложения</h2><dl className="mt-3 grid gap-x-5 gap-y-2 text-sm sm:grid-cols-[9rem_1fr]">{terms.map(([label, value]) => <div className="contents" key={label}><dt className="font-semibold text-zinc-700">{label}</dt><dd className="text-zinc-600">{value}</dd></div>)}</dl></section> : null; }
function Total({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 py-1 text-sm"><span className="text-zinc-600">{label}</span><span className="font-semibold">{value}</span></div>; }
function Label({ children }: { children: React.ReactNode }) { return <p className="text-[10px] font-semibold uppercase tracking-wide text-emerald-700">{children}</p>; }
function isProductProposalLine(line: CustomerProposalDto["sections"][number]["lines"][number]) { return line.lineType === "product" || (!line.lineType && Boolean(line.sku || line.imageUrl)); }
function money(value: number, currency: string) { return new Intl.NumberFormat("ru-RU", { style: "currency", currency, minimumFractionDigits: 2 }).format(value); }
function formatNumber(value: number) { return new Intl.NumberFormat("ru-RU", { maximumFractionDigits: 3 }).format(value); }
function formatDate(value: string) { return new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }
