"use client";

import { Save, Settings2, X } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { saveEstimateProposalSettingsAction } from "../actions/proposal.actions";
import type { ProposalSettings, ProposalTemplate } from "../types";
import { getEstimatesCopy, usePartnerLocale, type EstimatesCopy } from "../../partner-locale";

export function ProposalControls({ estimateId, revision, selectedTemplateId, templates, initialSettings }: { estimateId: string; revision: number; selectedTemplateId: string | null; templates: ProposalTemplate[]; initialSettings: ProposalSettings }) {
  const copy = getEstimatesCopy(usePartnerLocale());
  const router = useRouter(); const [open, setOpen] = useState(false); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null);
  const [templateId, setTemplateId] = useState(selectedTemplateId); const [settings, setSettings] = useState(initialSettings); const [currentRevision, setCurrentRevision] = useState(revision);
  const selectTemplate = (id: string) => { setTemplateId(id); const template = templates.find((item) => item.id === id); if (template) setSettings(template.configuration); };
  const save = () => startTransition(async () => { const result = await saveEstimateProposalSettingsAction(estimateId, { expectedRevision: currentRevision, templateId, settings }); setMessage(result.success ? copy.operationSucceeded : copy.operationFailed); if (result.success) { setCurrentRevision(result.data.revision); router.refresh(); } });
  return <><div className="sticky top-0 z-30 border-b border-zinc-200 bg-white/95 px-4 py-3 backdrop-blur print:hidden"><div className="mx-auto flex max-w-[210mm] flex-wrap items-center justify-between gap-2"><Link className={secondary} href={`/cabinet/estimates/${estimateId}`}>← {copy.backToEstimate}</Link><button className={secondary} onClick={() => setOpen(true)} type="button"><Settings2 className="size-4" />{copy.designSettings}</button></div>{message && <p aria-live="polite" className="mx-auto mt-2 max-w-[210mm] text-sm text-zinc-600">{message}</p>}</div>{open && <div aria-modal="true" className="fixed inset-0 z-50 flex justify-end bg-black/30 print:hidden" role="dialog"><div className="h-full w-full max-w-xl overflow-y-auto bg-white p-5 shadow-xl"><header className="flex items-center justify-between border-b border-zinc-200 pb-4"><div><p className="text-xs font-semibold uppercase text-emerald-700">{copy.commercialProposal}</p><h2 className="mt-1 text-lg font-semibold">{copy.documentDesign}</h2></div><button aria-label={copy.cancel} className="p-2" onClick={() => setOpen(false)} type="button"><X className="size-5" /></button></header><div className="space-y-4 py-5"><Field label={copy.template}><select className={inputClass} onChange={(event) => selectTemplate(event.target.value)} value={templateId ?? ""}>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></Field><TextField label={copy.heading} maxLength={200} onValue={(title) => setSettings({ ...settings, title })} value={settings.title} /><TextArea label={copy.introduction} onValue={(introduction) => setSettings({ ...settings, introduction })} value={settings.introduction} /><TextField label={copy.footerNote} maxLength={1000} onValue={(footerNote) => setSettings({ ...settings, footerNote })} value={settings.footerNote} /><fieldset className="grid gap-2 border-t border-zinc-200 pt-4 sm:grid-cols-2"><legend className="mb-2 text-sm font-semibold">{copy.display}</legend>{proposalToggles(copy).map(([key, label]) => <label className="flex items-center gap-2 text-sm" key={key}><input checked={settings[key]} onChange={(event) => setSettings({ ...settings, [key]: event.target.checked })} type="checkbox" />{label}</label>)}</fieldset></div><footer className="sticky bottom-0 flex justify-end gap-2 border-t border-zinc-200 bg-white py-4"><button className={secondary} onClick={() => setOpen(false)} type="button">{copy.cancel}</button><button className={primary} disabled={pending} onClick={save} type="button"><Save className="size-4" />{copy.save}</button></footer></div></div>}</>;
}
function proposalToggles(copy: EstimatesCopy): Array<[keyof Pick<ProposalSettings, "showProductImages" | "showSku" | "showUnitPrice" | "showLineDiscount" | "showSectionSubtotals" | "showVatBreakdown" | "showPartnerLogo">, string]> { return [["showProductImages", copy.productImages], ["showSku", copy.skuCodes], ["showUnitPrice", copy.unitPrice], ["showLineDiscount", copy.rowDiscount], ["showSectionSubtotals", copy.sectionSubtotals], ["showVatBreakdown", copy.vatBreakdown], ["showPartnerLogo", copy.partnerLogo]]; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-zinc-700"><span className="mb-1 block">{label}</span>{children}</label>; }
function TextField({ label, value, onValue, maxLength }: { label: string; value: string; onValue: (value: string) => void; maxLength: number }) { return <Field label={label}><input className={inputClass} maxLength={maxLength} onChange={(event) => onValue(event.target.value)} value={value} /></Field>; }
function TextArea({ label, value, onValue }: { label: string; value: string; onValue: (value: string) => void }) { return <Field label={label}><textarea className={`${inputClass} min-h-20`} maxLength={4000} onChange={(event) => onValue(event.target.value)} value={value} /></Field>; }
const inputClass = "w-full rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100";
const primary = "inline-flex min-h-11 items-center justify-center gap-2 rounded-md bg-emerald-700 px-4 text-sm font-semibold text-white disabled:opacity-50";
const secondary = "inline-flex min-h-11 items-center justify-center gap-2 rounded-md border border-zinc-300 bg-white px-3 text-sm font-semibold text-zinc-700";
